### ISSUE TITLE
Fill Individual Modules

### ISSUE THREAD

**Issue by haiiliin** [haiiliin/abqpy#1077]
Currently, most of the individual modules are empty. 

Inspecting objects in the Abaqus command line seems a way to do it (see https://github.com/haiiliin/abqpy/pull/1068#discussion_r964320659), for example, in Abaqus 2021, `dir(sketch)` returns: `['ALL_EDGES', 'AUTOCAD', 'AXISYM', 'BOTTOM', 'CLOCKWISE', 'COPLANAR_EDGES', 'COUNTERCLOCKWISE', 'ConstrainedSketchConstraintType', 'ConstrainedSketchDimensionType', 'ConstrainedSketchGeometryType', 'ConstrainedSketchImageOptionsType', 'ConstrainedSketchOptionsType', 'ConstrainedSketchParameterType', 'ConstrainedSketchType', 'ConstrainedSketchVertexType', 'ConstrainedSketcherOptionsType', 'DEFAULT', 'FeatureSketchType', 'JAMA', 'LEFT', 'MSBO', 'PARAMETRIC_DATA', 'REGULAR', 'RIGHT', 'SOLIDWORKS', 'STANDALONE', 'STANDALONENOSHOW', 'STANDARD', 'SUPERIMPOSE', 'Sketch', 'SketchDimensionType', 'SketchGeometryType', 'SketchOptionsType', 'SketchTransform', 'SketchTransform1', 'SketchTransformType', 'SketchType', 'SketchVertexType', 'SketcherOptionsType', 'THREED_DATA', 'TOP', 'TransformType', '__builtins__', '__doc__', '__name__', '__package__', 'part']`.

**Comment by Diogo-Rossi** [comment]
The snippet bellow creates a external file with information of each attribute in the module `sketch`.

It could be used in the other modules.

```python
with open('file.csv','w') as fd:
    fd.write("name, type, repr\n")
    for att in dir(sketch):
        fd.write(att + "," + str(type(getattr(sketch,att))) + "," + str(getattr(sketch,att)) + '\n')
```

**Comment by haiiliin** [comment]
Wow, great idea! We can also get the docstring by __doc__ if there are any. And if it is a class, we may also need to get the information of the attributes and methods.
