### ISSUE TITLE
Error when using `*` in installation

### ISSUE THREAD

**Issue by Diogo-Rossi** [haiiliin/abqpy#1105]
I tried to install `abqpy` with [Install A Specific Version](https://abqpy.haiiliin.com/en/v2021/getting_started.html#install-a-specific-version) using `*` to match specific version.
```
pip install abqpy==2021.*.*
```
But it gave me the following error message.
```
ERROR: Could not find a version that satisfies the requirement abqpy==2021.*.* (from versions: 2016a0, 2016a1, 2016a2, 2016a3, 2016a4, 2016a5, 2016a6, 2016a7, 2016a8, 2016a10, 2016.0, 2016.1, 2016.1.1, 2016.1.2, 2016.2.0, 2016.2.1, 2016.2.2, 2016.2.3, 2016.2.4, 2016.2.5, 2016.2.6, 2017a5, 2017a6, 2017a7, 2017a8, 2017a10, 2017.0, 2017.1, 2017.1.1, 2017.1.2, 2017.2.0, 2017.2.1, 2017.2.2, 2017.2.3, 2017.2.4, 2017.2.5, 2017.2.6, 2018a6, 2018a7, 2018a8, 2018a9, 2018a10, 2018.0, 2018.1, 2018.1.1, 2018.1.2, 2018.2.0, 2018.2.1, 2018.2.2, 2018.2.3, 2018.2.4, 2018.2.5, 2018.2.6, 2019a7, 2019a8, 2019a9, 2019a10, 2019.0, 2019.1, 2019.1.1, 2019.1.2, 2019.2.0, 2019.2.1, 2019.2.2, 2019.2.3, 2019.2.4, 2019.2.5, 2019.2.6, 2020a8, 2020a9, 2020a10, 2020.0, 2020.1, 2020.1.1, 2020.1.2, 2020.2.0, 2020.2.1, 2020.2.2, 2020.2.3, 2020.2.4, 2020.2.5, 2020.2.6, 2021a9, 2021a10, 2021.0, 2021.1, 2021.1.1, 2021.1.2, 2021.2.0, 2021.2.1, 2021.2.2, 2021.2.3, 2021.2.4, 2021.2.5, 2021.2.6, 2022a10, 2022.0, 2022.1, 2022.1.1, 2022.1.2, 2022.2.0, 2022.2.1, 2022.2.2, 2022.2.3, 2022.2.4, 2022.2.5, 2022.2.6)
ERROR: No matching distribution found for abqpy==2021.*.*
```
Is that the correct way to use it, or am I doing something wrong?

**Comment by haiiliin** [comment]
How about using `pip install abqpy==2021.*`?

**Comment by haiiliin** [comment]
`pip install abqpy==2021.*` seems the right way, in the README.md, I suggest this, but I may make a mistake in the documentation.

**Comment by haiiliin** [comment]
If so, we need to change it every time we publish a new release, I found it annoying so I just leave it like this.

**Comment by haiiliin** [comment]
May be we can use a workflow like `find and replace` to change it before publishing.

**Comment by haiiliin** [comment]
> How about using `pip install abqpy==2021.*`?

This is a strange behavior.

**Comment by haiiliin** [comment]
> > How about using `pip install abqpy==2021.*`?
> 
> Yes! That worked. BTW, in the documentation, it is suggesting an older version
> 
> ```
> pip install abqpy==2021.1.1
> ```
> 
> Maybe, there is a way to put the current version in this suggestion

I came up with a soution in #1107.
