### ISSUE TITLE
Installation not installing dependency `ipynbname`

### ISSUE THREAD

**Issue by Diogo-Rossi** [haiiliin/abqpy#1106]
I tried to install with the command
```cmd
pip install abqpy==2021.2.6
```
And it did install correctly, but not included the dependency `ipynbname`.
```
Collecting abqpy==2021.2.6
  Using cached abqpy-2021.2.6-py3-none-any.whl (1.6 MB)
Requirement already satisfied: typing-extensions in c:\... (from abqpy==2021.2.6) (4.3.0)
Requirement already satisfied: setuptools-scm in c:\... (from abqpy==2021.2.6) (7.0.5)
Requirement already satisfied: tomli>=1.0.0 in c:\... (from setuptools-scm->abqpy==2021.2.6) (2.0.1)
Requirement already satisfied: setuptools in c:\... (from setuptools-scm->abqpy==2021.2.6) (61.2.0)
Requirement already satisfied: packaging>=20.0 in c:\... (from setuptools-scm->abqpy==2021.2.6) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\... (from packaging>=20.0->setuptools-scm->abqpy==2021.2.6) (3.0.4)
Installing collected packages: abqpy
Successfully installed abqpy-2021.2.6
```

I've understood from [Installation](https://abqpy.haiiliin.com/en/v2021/getting_started.html#installation) instruction that by using `conda` we need to install `ipynbname` previously, but with `pip` that is not necessary. Did I misunderstood?

**Comment by haiiliin** [comment]
This is a mistake, initially I put `ipynbname` in `install_requires` in `setup.py` , but when I use the GitHub workflows to publish the package automatically, there is always a dependency error and I haven't investigated carefully at that time, so I remove it in `setup.py`, regard it as optional requirements, but I forget to modify the corresponding documentation here.
