### ISSUE TITLE
Use `::` instead of `code-block` directive to simplify the code

### ISSUE THREAD

**Issue by haiiliin** [haiiliin/abqpy#1265]
I just found out that VS Code render the content of code blocks using others ways to [show code example](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#showing-code-examples) with Sphinx.

The [reST literal blocks](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#rst-literal-blocks) and the [reST doctest blocks](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#doctest-blocks) works fine.

![image](https://user-images.githubusercontent.com/57204023/189513687-0cdb841a-cbaa-464b-b6ee-9a075e41ed07.png)

_Originally posted by @Diogo-Rossi in https://github.com/haiiliin/abqpy/discussions/1131#discussioncomment-3617187_

**Comment by Diogo-Rossi** [comment]
@haiiliin Thanks for this update! It will help a lot!
