### ISSUE TITLE
Handle Command Line Arguments

### ISSUE THREAD

**Issue by haiiliin** [haiiliin/abqpy#1269]
### Command line arguments processing

This "final idea" came while concluding the #1104. 

The question I ask myself is: What if I want to use the `session.openOdb` method without a GUI?
(i.e. `abaqus cae -noGUI script.py` inside the `session.openOdb`)

Another question was: what if I want to use the `mdb.saveAs` method with a GUI? (`abaqus cae script=script.py` in the `mdb.saveAs`)

Then I thought that all the abaqus command line options could be set as arguments to run the script.

The main option `script=...` could be fixed, and the others inputted as arguments to the python script.

One possible approach would be:

In both `mdb.saveAs` and `session.openOdb`:
```python
os.system(f"{abaqus} cae script={sys.argv[0]} {sys.argv[1]} {sys.argv[2]} ... ")
```
Then, if I want a `noGUI` run, I would call:
```bash
python3 myscript.py -noGUI
```
But the other options would also be possible, including the removed `database` option:
```
abaqus cae
    [database=database-file]
    [replay=replay-file]
    [recover=journal-file]
    [startup=startup-file]
    [script=script-file]
    [noGUI=noGUI-file]
    [noenvstartup]
    [noSavedOptions]
    [noSavedGuiPrefs]
    [noStartupDialog]
    [custom=script-file]
    [guiTester=GUI-script]
    [guiRecord]
    [guiNoRecord]
```

_Originally posted by @Diogo-Rossi in https://github.com/haiiliin/abqpy/discussions/1131_

**Comment by haiiliin** [comment]
### Possible solutions

- [x] Pass arguments to `python` and process it in [`abqpy.abaqus.run()`](https://github.com/haiiliin/abqpy/blob/2023/src/abqpy/abaqus.py#L9-L69). 
- [ ] Develop a VSCode/PyCharm `Abaqus/Python Runner` extension to run the script, see https://github.com/haiiliin/abqpy/discussions/1131#discussioncomment-3616283.
- [x] Use an individual command line application `abqpy` to run the script, see https://github.com/haiiliin/abqpy/discussions/1131#discussioncomment-3618817, implemented in #1435, improved in #2210.
- [ ] Use a global variable to store the command option, see https://github.com/haiiliin/abqpy/discussions/1131#discussioncomment-3620868. 
- [x] Use environment variables such as `ABAQUS_BAT_PATH` to set the options, or load temporary environment variables by [python-dotenv](https://pypi.org/project/python-dotenv/), see https://github.com/haiiliin/abqpy/discussions/1131#discussioncomment-3621941, implemented in #2608 (`ABAQUS_COMMAND_OPTIONS` Environment Variable).

**Comment by Diogo-Rossi** [comment]
> ### Possible solutions
> * [ ]  Pass arguments to `python` and process it in [`abqpy.abaqus.run()`](https://github.com/haiiliin/abqpy/blob/main/src/abqpy/abaqus.py#L5-L36).
> * [ ]  Develop a VSCode/PyCharm `Abaqus/Python Runner` extension to run the script
> * [ ]  Use a individual command line application `abqpy` to run the script
> * [ ]  Use a global variable to store the command option
> * [ ]  Use environment variables such as `ABAQUS_BAT_PATH` to set the options, or load temporary environment variables by [python-dotenv](https://pypi.org/project/python-dotenv/)

I found out a new solution that could be applied:

To use `abqpy` as ["module"](https://docs.python.org/3/using/cmdline.html#cmdoption-m) with the `-m` flag.
```
python3 -m abqpy opt1 opt2 script.py
```

I saw an example usage with `IPython` module, for instance:
```
python3 -m IPython -i script.py
```
in this case, `-i` is an option of `IPython`

**Comment by haiiliin** [comment]
Basically, it is a command line application.

**Comment by Diogo-Rossi** [comment]
> Basically, it is a command line application.

It is a sort of. But could run with `python3` interpreter.

**Comment by haiiliin** [comment]
For example, the [`numba`](https://github.com/numba/numba/blob/527a3f48d81930bdccf1dea7561af1b62640e6c3/setup.py#L415) command line script.

**Comment by Diogo-Rossi** [comment]
Regarding https://github.com/haiiliin/abqpy/pull/1435#issue-1375361651, I have some remarks.
```
usage: abqpy [-h] [-n] [-m {cae,python}] script ...

The abqpy command line interface

positional arguments:
  script                the python script to run
  others                other arguments that will be passed to the abaqus command

options:
  -h, --help            show this help message and exit
  -n, --noGUI           run abaqus command in batch mode
  -m {cae,python}, --mode {cae,python}
                        option to run Abaqus, either cae or python, by default cae
```
___
Wasn't this the default option?
```
  -n, --noGUI           run abaqus command in batch mode
```
If so. Wouldn't that change to something like  `-g, --GUI             run abaqus cae command in GUI mode`
___
Maybe the last option could be something like this:
```
  -m, --mode [(cae [<options>] | python [<options>])]
                        option to run Abaqus, either cae or python mode, by default cae.
                        <options> are parameters specific to each procedure. Consult Abaqus docs
```
The following would be `abaqus cae` [parameters](https://help.3ds.com/2022/English/DSSIMULIA_Established/SIMACAEEXCRefMap/simaexc-c-caeproc.htm?contextscope=all&id=10b7dd92afde4b3695e76527b429eba8#simaexc-c-caeproc-t-cmdsummary1) (not including `noGUI` option):
<details>
<summary>abaqus cae</summary>

```
abaqus cae
    [database=database-file]
    [replay=replay-file]
    [recover=journal-file]
    [startup=startup-file]
    [script=script-file]
    [noenvstartup]
    [noSavedOptions]
    [noSavedGuiPrefs]
    [noStartupDialog]
    [custom=script-file]
    [guiTester=GUI-script]
    [guiRecord]
    [guiNoRecord]
```

</details>

And the following would be `abaqus python` [parameters](https://help.3ds.com/2022/English/DSSIMULIA_Established/SIMACAEEXCRefMap/simaexc-c-pythonproc.htm?contextscope=all&id=b5f111e13c6a4311a0fc5623bb4fa45c#simaexc-c-pythonproc-t-cmdsummary1) (not including `script` value):
<details>
<summary>abaqus python </summary>

```
abaqus python 
    [sim=sim_file_name]
    [log=log_file_name]
```

</details>

Everything after the `script` parameter would then be arguments passed to the script.
___

With this, the summary becomes:
```
usage: abqpy [-h] [-g] [-m [(cae [<options>] | python [<options>])]] script [<args>]

The abqpy command line interface

positional arguments:
  script                the python script to run
  [<args>]              arguments that will be passed to the python script

options:
...
```
What do you think?

**Comment by haiiliin** [comment]
Nice idea, but I don't if it can be implemented, especially the second thought you talked, I am not so familiar with the `argparse` module.

**Comment by haiiliin** [comment]
> Wasn't this the default option?
> ```
>   -n, --noGUI           run abaqus command in batch mode
> ```
> If so. Wouldn't that change to something like  `-g, --GUI             run abaqus cae command in GUI mode`

Makes sense

**Comment by Diogo-Rossi** [comment]
@haiiliin , I was working on this subject and end up with 2 possible solutions for the command line interface:

<details>
<summary>Option 1</summary>

```sh
usage: abqpy.py [-h] [--] [-g [cae-options ...] | -n [cae-options ...] | -p [python-options ...]] [script] [args ...]        

The abqpy command line interface

positional arguments:
  script                the python script to run
  args                  arguments that will be passed to the python script

optional arguments:
  -h, --help            show this help message and exit
  --                    option to pass the script after abaqus command arguments
  -g [cae-options ...], --cae-gui [cae-options ...]
                        command line options used to run abaqus cae command with the graphical user interface (GUI mode)     
  -n [cae-options ...], --cae-no-gui [cae-options ...]
                        command line options used to run abaqus cae command without the graphical user interface (noGUI mode)
  -p [python-options ...], --python [python-options ...]
                        command line options used to run abaqus python command

Options
=======
The default execution for abaqus command line options is to use `-n` (noGUI mode)
with no additional options.

When using abaqus command options (`-g`, `-n`, `-p`) together with the python `script`,
AND the script is passed after abaqus command line options, you may need to specify `--`
before the script filename, to prevent abqpy from attempting to parse it to abaqus.
That is not necessary if you pass the filename before abaqus command line options.

`abaqus cae` command possible options:

    database=database-file
    replay=replay-file
    recover=journal-file
    startup=startup-file
    noenvstartup
    noSavedOptions
    noSavedGuiPrefs
    noStartupDialog
    custom=script-file
    guiTester=GUI-script
    guiRecord
    guiNoRecord

`abaqus python` command possible options:
    sim=sim_file_name
    log=log_file_name

Please, refer to abaqus documentation for details in each option.

```
</details>

<details>
<summary>Option 2</summary>

```sh
usage: abqpy.py [-h] [--] [-m {gui,nogui,python}] [-a [abq-options ...]] [script] [args ...]

The abqpy command line interface

positional arguments:
  script                the python script to run
  args                  arguments that will be passed to the python script

optional arguments:
  -h, --help            show this help message and exit
  --                    option to pass the script after abaqus command arguments
  -m {gui,nogui,python}, --mode {gui,nogui,python}
                        option to run Abaqus command, by default nogui
  -a [abq-options ...], --abq-options [abq-options ...]
                        command line options that will be passed to the abaqus command      

Options
=======
The default execution for abaqus command line options is to use `-m nogui` (noGUI mode)     
with no additional options.

When using abaqus command line options (`-a`) together with the python `script`,
AND the script is passed after abaqus command line options, you may need to specify `--`    
before the script filename, to prevent abqpy from attempting to parse it to abaqus.
That is not necessary if you pass the filename before abaqus command line options.

`abaqus cae` command possible options:

    database=database-file
    replay=replay-file
    recover=journal-file
    startup=startup-file
    noenvstartup
    noSavedOptions
    noSavedGuiPrefs
    noStartupDialog
    custom=script-file
    guiTester=GUI-script
    guiRecord
    guiNoRecord

`abaqus python` command possible options:
    sim=sim_file_name
    log=log_file_name

Please, refer to abaqus documentation for details in each option.

```
</details>

In **Option 1**, the command line is smaller, but the interface is a little more complex.
If I want to run with `gui` mode and add the `database` option, the command becomes:
```sh
abqpy myscript.py -g database=filename.odb
```
In **Option 2**, the interface is simpler, but the command line is bigger.
If I want to run the same as before, the command becomes:
```sh
abqpy myscript.py -m gui -a database=filename.odb
```

Do you agree with anyone? Which one do you think is better?

**Comment by haiiliin** [comment]
Among these two options, I think the first one is better, more simple.

For reference, another possible solution is to use the subparsers, https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_subparsers:
```
abqpy gui|nogui|python [<options>]
```

**Comment by Diogo-Rossi** [comment]
> Among these two options, I think the first one is better, more simple.
> 
> For reference, another possible solution is to use the subparsers, https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_subparsers:
> 
> ```
> abqpy gui|nogui|python [<options>]
> ```

Yes, I've search the subparsers option too.
But I could not find a solution that passes the sub-command argument together with the python script and its arguments

**Comment by haiiliin** [comment]
> > Among these two options, I think the first one is better, more simple.
> > For reference, another possible solution is to use the subparsers, https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_subparsers:
> > ```
> > abqpy gui|nogui|python [<options>]
> > ```
> 
> Yes, I've search the subparsers option too. But I could not find a solution that passes the sub-command argument together with the python script and its arguments

At first, I was trying to implement the subparsers, but I know little about the argparse module, so I gave up.

**Comment by haiiliin** [comment]
I am reconsidering the idea of passing the command line arguments, is it really necessary? Why not using the official abaqus command if we need to pass extra arguments, if we provide a new command line interface `abqpy`, why should we use the `abqpy` instead of `abaqus` directly?

**Comment by Diogo-Rossi** [comment]
> I am reconsidering the idea of passing the command line arguments, is it really necessary? Why not using the official `abaqus` command if we need to pass extra arguments? If we provide a new command line interface `abqpy`, why should we use the `abqpy` instead of `abaqus` directly?

Good question! I had some thoughts about that too. 

The first advantage I thought in passing command line arguments with `abqpy` (either by `rcParams` or by a new cli) is to use the python3 interpreter inside the python IDE, which can be configured to launch either option.

Another advantage I found is when we use the `ABAQUS_BAT_PATH` variable, that may be set to server path, making the abaqus command a littler more longer to use directly.

But, if you think it is not worth, that is ok.

**Comment by haiiliin** [comment]
> The first advantage I thought in passing command line arguments with abqpy (either by rcParams or by a new cli) is to use the python3 interpreter inside the python IDE, which can be configured to launch either option.

It is. If you have worked out something about this, you can create a pull request, it is better than nothing.

**Comment by Diogo-Rossi** [comment]
> It is. If you have worked out something about this, you can create a pull request, it is better than nothing.

Right. Thank you!

**Comment by Diogo-Rossi** [comment]
> * [ ]  Use environment variables such as `ABAQUS_BAT_PATH` to set the options, or load temporary environment variables by [python-dotenv](https://pypi.org/project/python-dotenv/), see [Maybe use command line arguments to `abaqus cae` command #1131 (reply in thread)](https://github.com/haiiliin/abqpy/discussions/1131#discussioncomment-3621941).
___
#### Comment in thread

> Yes, I thought of an environment variable too. But I couldn't think of a way to store all those options in one single environment variable.

We can define a environment variable like `ABAQUS_COMMAND_OPTIONS`, users can put all the options here, or define multiple individual environment variables like `ABAQUS_NOGUI`. 

Another option is to define `.env` file locally and use `dotenv` to load the local environment file in abaqus/__init__.py file

_Originally posted by @haiiliin in https://github.com/haiiliin/abqpy/discussions/1131#discussioncomment-3622110_
    
___
I just found a way to use this option as an alternative to the CLI, with the [`ast.literal_eval`](https://docs.python.org/3/library/ast.html#ast.literal_eval) function.
I'll put a test in an separate branch.

**Comment by altaflone** [comment]
in command prompt i wrote the command as directed in documentation .

first this:   abaqus fetch job=viewer_tutorial

then: python filename.py  command...


why am i getting errors? am i doing anything wrong here. kindly help me with situation



thank you

altaf

**Comment by haiiliin** [comment]
> in command prompt i wrote the command as directed in documentation .
> 
> first this: abaqus fetch job=viewer_tutorial
> 
> then: python filename.py command...
> 
> why am i getting errors? am i doing anything wrong here. kindly help me with situation
> 
> thank you
> 
> altaf

Can you provide detailed information about the error message?

**Comment by altaflone** [comment]
Thank you sir for reply.

i did follow the steps as explained in the documentation.

i downloaded the sample viewerOpenOdbAndContour.py file from the website.

then i open my cmd ran the line : abaqus fetch job=viewer_tutorial

then i ran the command line: python viewerOpenOdbAndContour.py in my cmd

the error i get is in line 13 of the .py file

attribute error: 'session' object has no attribute 'viewport'

kindly help sir , what am i doing wrong.

thank you sir


altaf

**Comment by haiiliin** [comment]
> attribute error: 'session' object has no attribute 'viewport'

You mean the error occurred here:
https://github.com/haiiliin/abqpy/blob/a974863a7e9932d216f8207f2beb24bf0f51dafb/examples/Abaqus/viewerOpenOdbAndContour.py#L39-L40

The code should be `session.Viewport` with a capital `V` but you mentioned that the error message is `attribute error: 'session' object has no attribute 'viewport'` with a lower `v`, I don't know if you download the script correctly or you just misspelled the error message, could do you please just copy all the raw message from your cmd?

**Comment by altaflone** [comment]
Microsoft Windows [Version 10.0.22000.318]
(c) Microsoft Corporation. All rights reserved.

```
C:\Users\hp\Desktop\Abaqus> abaqus fetch job=viewer_tutorial

Intel(R) MPI Library 2017 Update 2 for Windows* Target Build Environment for Intel(R) 64 applications
Copyright (C) 2007-2017 Intel Corporation. All rights reserved.

Copyright (C) 1985-2017 Intel Corporation. All rights reserved.
Intel(R) Compiler 17.0 Update 2 (package 187)

Abaqus FETCH job viewer_tutorial
  fetching: viewer_tutorial.odb

C:\Users\hp\Desktop\Abaqus> python vieweroOpenOdbAndContour.py
python: can't open file 'C:\Users\hp\Desktop\Abaqus\vieweroOpenOdbAndContour.py': [Errno 2] No such file or directory

C:\Users\hp\Desktop\Abaqus>python viewerOpenOdbAndContour.py
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\Abaqus\viewerOpenOdbAndContour.py", line 13, in <module>
    myViewport=session.Viewport(name='Print a contour plot',
AttributeError: 'Session' object has no attribute 'Viewport'

C:\Users\hp\Desktop\Abaqus>
```

**Comment by haiiliin** [comment]
Which version of `abqpy` are you using? you can use `pip show abqpy` to show the version information. If you are using a very old version, I suggest you upgrade `abqpy` by `pip install -U abqpy`.

**Comment by altaflone** [comment]
sir , i installed just today with conda 

conda install -c haiiliin abqpy

**Comment by haiiliin** [comment]
You'd better install it with `pip` because we have some issues with `conda`, and the latest version of `abqpy` is not distributed in `conda`.

**Comment by altaflone** [comment]
Thank you sir for the suggestion and help.

Thank you

altaf

**Comment by altaflone** [comment]
Thank you for your advice. i could solve the example problems perfectly. 

Thank you a lot. god bless you.

sir, i have a one question totally unrelated to this discussion whatsoever. 

sir, their is the repository [https://github.com/erolsson/case_hardening_simulation] , which is related to my research problem.
 
sir, for quite some time i have time i have been trying to get it but i totally cant get the simulation running.

i have installed all his extensions like 

read input file
abaqus python interface and other setup files.

but i fail to understand the working process behind it. also no documentation is provided.

sir, i humbly and sincerely request you to have look at it , if possible and help me through it.

i am extremely for being out of line maybe but i really need help here sir as i am trying to solve it for quite some time now.

Thank you sir

altaf
