### ISSUE TITLE
Abaqus Error in locating file when used with relative path

### ISSUE THREAD

**Issue by Diogo-Rossi** [haiiliin/abqpy#1286]
When we use relative path to the python script (`python3 myscript.py`)
&
Change the work directory on the fly (to run multiple models in different folders)

Abaqus can not locate the script file.

## Example
Given the small test

<details>
<summary><b>Contents of `myscript.py`</b></summary>

```python
# contents of `myscript.py`
import os
import sys
import shutil
import time

from abaqus import *
from abaqusConstants import *
from caeModules import *
from driverUtils import *

def make_dir_model(name):
    if os.path.exists(os.path.abspath(name)):
        shutil.rmtree(name)
        time.sleep(1) # wait a 1 sec
    os.mkdir(name)

def test_multimodels():
    model_names = ['Model1', 'Model2', 'Model3']
    for name in model_names:
        make_dir_model(name)
        os.chdir(name)
        mdb.saveAs('{0}.cae'.format(name))
        os.chdir('../')

if __name__ == "__main__":
    test_multimodels()
```

</details>

The script above runs OK when using the absolute path:
```python
python3 absolute/path/to/myscript.py
```

But gives an error in Abaqus when using relative path:
```python
python3 myscript.py
```
Because Abaqus can not locate the script file in this case
```
Abaqus Error: The following file(s) could not be located: absolute\path\to\Model1\myscript.py
Abaqus Error: The following file(s) could not be located: absolute\path\to\Model2\myscript.py
Abaqus Error: The following file(s) could not be located: absolute\path\to\Model3\myscript.py
```
That happens because the resolution of the function
```
os.path.abspath(sys.argv[0])
```
is to the Current Work Directory (CWD) when the `sys.argv[0]` is not absolute.

## Possible Solution

Replace `sys.argv[0]` by the top level script path (`__main__.__file__`) inside the `run()` function

**Comment by haiiliin** [comment]
You are right, and I believe `__main__.__file__` would solve this problem.

**Comment by haiiliin** [comment]
Instead of using `__main__.__file__` directly, I would use `sys.modules['__main__'].__file__` since PyCharm tells me `Python 3.7, 3.8 ... 3.11 do not have module __main__` through I don't know why. But anyway.

**Comment by Diogo-Rossi** [comment]
> Instead of using `__main__.__file__` directly, I would use `sys.modules['__main__'].__file__` since PyCharm tells me `Python versions 3.6, 3.7, 3.8, 3.9, 3.10, 3.11 do not have module __main__ ` through I don't know why.

I think you have to `import __main__` before.

**Comment by haiiliin** [comment]
I know that, it works, PyCharm just raise a warning.

**Comment by Diogo-Rossi** [comment]
oh, I see. I think that is an issue in PyCharm itself. Look [this](https://youtrack.jetbrains.com/issue/PY-39598/Incorrect-error-message-for-import-main) and [this](https://youtrack.jetbrains.com/issue/PY-5686#focus=streamItem-27-555645.0-0)

**Comment by haiiliin** [comment]
Right, `sys.modules['__main__'].__file__` will totally work and it is identical.
