### ISSUE TITLE
Issues about the `openOdb` implementations

### ISSUE THREAD

**Issue by haiiliin** [haiiliin/abqpy#1360]
### Original Idea of not providing the `database` option in `openOdb`

> I tried this initially, didn't work, didn't know why, and then I use the later one. And we can't get the output using `-noGUI` option.

Yes, I made the wrong question. The line I was talking about is
```python
os.system(f"{abaqus} cae script={filePath}")
```
Without the `-noGUI` option.

I've made a test and got the output, but I needed to add the following lines after `session.openOdb`:
```python
o = session.odbs['Job-1.odb']
session.viewports['Viewport: 1'].setValues(displayedObject=o)
```

Then, the original whole test code becomes:

```python
from abaqus import *
from abaqusConstants import *
from driverUtils import *
import numpy as np

executeOnCaeStartup()

# Open output database
odb = session.openOdb('Job-1.odb')

o = session.odbs['Job-1.odb']
session.viewports['Viewport: 1'].setValues(displayedObject=o)

# Extract output data
dataList = session.xyDataListFromField(odb=odb, outputPosition=NODAL,
                                       variable=(('U', NODAL, ((COMPONENT, 'U3'),)),),
                                       nodeSets=('INSTANCE.SET-TOP', ))
data = np.array(dataList[0])
np.savetxt('data.csv', data, header='time,U3', delimiter=',', comments='')
```
And I don't need to provide the database in the Abaqus command.
Without those 2 additional lines, there is a error and we can't get the output.

_Originally posted by @Diogo-Rossi in https://github.com/haiiliin/abqpy/issues/1104#issuecomment-1241109529_

### Issues

@Diogo-Rossi Are you sure this is working? I just tested it and it raise a `TypeError`:
```python
TypeError: displayedObject; found Odb, expecting StubType, Part, ConstrainedSketch, Assembly, or XYPlot
File "C:/Users/Hailin/OneDrive/Documents/GitHub/abqpy/examples/compression-output.py", line 12, in <module>
    session.viewports['Viewport: 1'].setValues(displayedObject=o)
```

**Comment by haiiliin** [comment]
### Original Idea of `odbAccess.openOdb`

> I was thinking about that and I guessed some different modification in `odbAccess.openOdb` function.

The [`odbAccess.openOdb`](https://help.3ds.com/2022/english/dssimulia_established/SIMACAEKERRefMap/simaker-c-odbopenodbcommandpyc.htm?contextscope=all&id=9f0ec3921d15431997232cb3f25d285d#simaker-odbodbopenodbpyc) function is different from the [`session.openOdb`](https://help.3ds.com/2022/english/dssimulia_established/SIMACAEKERRefMap/simaker-c-odbopenodbcommandpyc.htm?contextscope=all&id=d16c67175beb4d0aa7584a7d4f2bfd5a#simaker-odbodbsesopenodbpyc).

The `odbAccess.openOdb` function can be run regardless of Abaqus CAE. See, for instance [this example](https://help.3ds.com/2022/english/dssimulia_established/SIMACAECMDRefMap/simacmd-c-odbintrosimpleexapyc.htm?contextscope=all&id=f32d4a1eda50408b96561de06760f215).
Its usage is simply `abaqus python odbRead.py`, so I think that the command in this function could be changed to the following:
```python
os.system(f"{abaqus} python {filePath}")
```
What do you think? 

In this way, the script doesn't use the Abaqus CAE kernel, which I think is the reason of two different functions with the same name.

_Originally posted by @Diogo-Rossi in https://github.com/haiiliin/abqpy/issues/1104#issuecomment-1240309844_

### Issue

What if I want to run the script in `GUI` mode when using the `odbAccess.openOdb` and also includes the `import abaqus`, because the `abaqus` module can't be imported in `noGUI` mode, in this condition, an `ImportError` will be raised:
```python
Traceback (most recent call last):
  File "C:\Users\Hailin\OneDrive\Documents\GitHub\abqpy\examples\compression-output.py", line 1, in <module>
    from abaqus import *
  File "SMAPython\SMAPytLibPy.m\src\site.py", line 120, in _numpyHook
    d = set()
  File "SMAPyaModules\SMAPyaAbqPy.m\src\abaqus.py", line 16, in <module>
ImportError: abaqus module may only be imported in the Abaqus kernel process
```

**Comment by Diogo-Rossi** [comment]
> ```python
> from abaqus import *
> from abaqusConstants import *
> from driverUtils import *
> import numpy as np
> 
> executeOnCaeStartup()
> 
> # Open output database
> odb = session.openOdb('Job-1.odb')
> 
> o = session.odbs['Job-1.odb']
> session.viewports['Viewport: 1'].setValues(displayedObject=o)
> 
> # Extract output data
> dataList = session.xyDataListFromField(odb=odb, outputPosition=NODAL,
>                                        variable=(('U', NODAL, ((COMPONENT, 'U3'),)),),
>                                        nodeSets=('INSTANCE.SET-TOP', ))
> data = np.array(dataList[0])
> np.savetxt('data.csv', data, header='time,U3', delimiter=',', comments='')
> ```
> 
> ### Issues
> @Diogo-Rossi Are you sure this is working? I just tested it and it raise a `TypeError`:
> 
> ```python
> TypeError: displayedObject; found Odb, expecting StubType, Part, ConstrainedSketch, Assembly, or XYPlot
> File "C:/Users/Hailin/OneDrive/Documents/GitHub/abqpy/examples/compression-output.py", line 12, in <module>
>     session.viewports['Viewport: 1'].setValues(displayedObject=o)
> ```

@haiiliin , Yes, I just tested that code right now, and it is working. I don't know why that `TypeError` was raised...

**Comment by haiiliin** [comment]
It is strange, in GUI mode, it work fine, but not with noGUI mode

**Comment by Diogo-Rossi** [comment]
> I tried these two commands,
> 
> ```
> abaqus cae noGUI=compression-output.py
> abaqus cae script=compression-output.py
> ```
> 
> The first one fails, the second one works.

I my case, both command works. In the second one it opens the Abaqus CAE GUI.

**Comment by Diogo-Rossi** [comment]
> What if I want to run the script in `GUI` mode when `odbAccess.openOdb` is used and also includes the `import abaqus`, because the `abaqus` module can't be imported in `noGUI` mode, in this condition, an `ImportError` will be raised:
> 
> ```python
> > abaqus python
> ...
> >>> import odbAccess
> >>> from abaqus import *
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "SMAPython\SMAPytLibPy.m\src\site.py", line 120, in _numpyHook
>   File "SMAPyaModules\SMAPyaAbqPy.m\src\abaqus.py", line 16, in <module>
> ImportError: abaqus module may only be imported in the Abaqus kernel process
> ```

Yes, I think that is expected. `abaqus` module can only be imported with `abaqus cae` command (in both modes `noGUI` and without `noGUI`). This module can't be imported in with `abaqus python` command.

I think the purpose of using `odbAccess.openOdb` is to access ODB file without `abaqus cae` command (i.e. not importing `abaqus` module, if done, will raise the `Abaqus kernel` error message). That is the reason I thought it would use `abaqus python` command.

That is what I conclude from the [documentation](https://help.3ds.com/2022/English/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-odbopenodbcommandpyc.htm?contextscope=all&id=9f0ec3921d15431997232cb3f25d285d#simaker-odbodbopenodbpyc) when it says 
>This method opens an existing output database (.odb) file and creates a new Odb object. You typically execute this method outside of Abaqus/CAE when, in most cases, only one output database is open at any time. For example,

For the situation of using Abaqus CAE, I think we can use the `session.openOdb`.

Do you have an example of using `odbAccess.openOdb` with `abaqus cae`?

**Comment by haiiliin** [comment]
> > What if I want to run the script in `GUI` mode when `odbAccess.openOdb` is used and also includes the `import abaqus`, because the `abaqus` module can't be imported in `noGUI` mode, in this condition, an `ImportError` will be raised:
> > ```python
> > > abaqus python
> > ...
> > >>> import odbAccess
> > >>> from abaqus import *
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> >   File "SMAPython\SMAPytLibPy.m\src\site.py", line 120, in _numpyHook
> >   File "SMAPyaModules\SMAPyaAbqPy.m\src\abaqus.py", line 16, in <module>
> > ImportError: abaqus module may only be imported in the Abaqus kernel process
> > ```
> 
> Yes, I think that is expected. `abaqus` module can only be imported with `abaqus cae` command (in both modes `noGUI` and without `noGUI`). This module can't be imported in with `abaqus python` command.
> 
> I think the purpose of using `odbAccess.openOdb` is to access ODB file without `abaqus cae` command (i.e. not importing `abaqus` module, if done, will raise the `Abaqus kernel` error message). That is the reason I thought it would use `abaqus python` command.
> 
> That is what I conclude from the [documentation](https://help.3ds.com/2022/English/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-odbopenodbcommandpyc.htm?contextscope=all&id=9f0ec3921d15431997232cb3f25d285d#simaker-odbodbopenodbpyc) when it says
> 
> > This method opens an existing output database (.odb) file and creates a new Odb object. You typically execute this method outside of Abaqus/CAE when, in most cases, only one output database is open at any time. For example,
> 
> For the situation of using Abaqus CAE, I think we can use the `session.openOdb`.
> 
> Do you have an example of using `odbAccess.openOdb` with `abaqus cae`?

How about just change the `session.openOdb` to `odbAccess`:
```python
from abaqus import *
from abaqusConstants import *
from driverUtils import *
import odbAccess
import numpy as np

executeOnCaeStartup()

# Open output database
odb = odbAccess.openOdb('Job-1.odb')

o = session.odbs['Job-1.odb']
session.viewports['Viewport: 1'].setValues(displayedObject=o)

# Extract output data
dataList = session.xyDataListFromField(odb=odb, outputPosition=NODAL,
                                       variable=(('U', NODAL, ((COMPONENT, 'U3'),)),),
                                       nodeSets=('INSTANCE.SET-TOP', ))
data = np.array(dataList[0])
np.savetxt('data.csv', data, header='time,U3', delimiter=',', comments='')
```

**Comment by Diogo-Rossi** [comment]
> How about just change the `session.openOdb` to `odbAccess.opdnOdb`:

That will not work in the current implementation. Because `odbAccess.opdnOdb` uses command `abaqus python` and, to `import abaqus` module, you need the command `abaqus cae`

The command `abaqus python` is described [here](https://help.3ds.com/2022/English/DSSIMULIA_Established/SIMACAEEXCRefMap/simaexc-c-pythonproc.htm?contextscope=all&id=5265b6f90927483684003987b54bc87e)

**Comment by Diogo-Rossi** [comment]
> > > I tried these two commands,
> > > ```
> > > abaqus cae noGUI=compression-output.py
> > > abaqus cae script=compression-output.py
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The first one fails, the second one works.
> > 
> > 
> > I my case, both command works. In the second one it opens the Abaqus CAE GUI.
> 
> That is so strange.

I'll check it out deeply.

**Comment by haiiliin** [comment]
But the script works in GUI mode

**Comment by Diogo-Rossi** [comment]
> I'll check it out deeply.

@haiiliin , I just tested the code in "interactive mode", with both GUI and `noGUI` mode, and it got no error.

#### Output of `noGUI` mode
```sh
> abaqus cae noGUI

Python 2.7.15 (default, Jul 25 2019, 08:13:50) [MSC v.1916 64 bit (AMD64)]
>>> from abaqus import *
>>> from abaqusConstants import *
>>> from driverUtils import *
>>> import numpy as np
>>> odb = session.openOdb('Job-1.odb')
>>> session.viewports['Viewport: 1'].setValues(displayedObject=odb)
>>> dataList = session.xyDataListFromField(odb=odb, outputPosition=NODAL,
...                                        variable=(('U', NODAL, ((COMPONENT, 'U3'),)),),
...                                        nodeSets=('INSTANCE.SET-TOP', ))
>>> data = np.array(dataList[0])
>>> if data.size > 0:
...     np.savetxt('data.csv', data, header='time,U3', delimiter=',', comments='')
...
>>> exit()
RT script done
```

#### Output of GUI mode

![image](https://user-images.githubusercontent.com/57204023/190182669-af96b0cb-82a3-4c34-a3dd-e73fc9650e65.png)

I don't if changes anything, but I'm using Abaqus 2021

**Comment by haiiliin** [comment]
I am also using abaqus 2021, don't know wht this happens

**Comment by Diogo-Rossi** [comment]
I just found out what the problem is. We need to import the `visualization` module.

I had a custom `onCaeStartup()` function that is called with

>```
>>>> executeOnCaeStartup()
> Executing "onCaeStartup()" in the site directory ...
> ```

I checked this function and it was importing `visualization` already. That is why I did not get the error.

**Comment by haiiliin** [comment]
I still don't understand why importing visualization would work. Can you explain in more detail? Why do you mean by custom `onCaeStartup()`?

**Comment by Diogo-Rossi** [comment]
> I still don't understand why importing visualization would work. Can you explain in more detail? Why do you mean by custom `onCaeStartup()`?

There is a [environment file](https://help.3ds.com/2022/english/dssimulia_established/SIMACAEILGRefMap/simailg-m-EnvUsing-sb.htm?contextscope=all&id=16d24bf4277c43adbf5b890fa8ed62c7) that can be customized to include a custom [`onCaeStartup()` function](https://help.3ds.com/2022/english/dssimulia_established/SIMACAEILGRefMap/simailg-c-envexaexample.htm?contextscope=all&id=09c8027a6c9641f3a666c12f9e5f7907), which I think is called by the `executeOnCaeStartup()`.

So I had already changed this function inside the `custom_v6.env` file to set a view port configuration (recording the script) and that could was running:
```python
import visualization
session.viewports['Viewport: 1'].view.setViewpoint(viewVector=(1, -1, 1), cameraUpVector=(0, 0, 1))
```
That is why I did not got the problems with visualization.

**Comment by haiiliin** [comment]
> ### Original Idea of using `abaqus python` in `odbAccess.openOdb`
> > I was thinking about that and I guessed some different modification in `odbAccess.openOdb` function.
> 
> The [`odbAccess.openOdb`](https://help.3ds.com/2022/english/dssimulia_established/SIMACAEKERRefMap/simaker-c-odbopenodbcommandpyc.htm?contextscope=all&id=9f0ec3921d15431997232cb3f25d285d#simaker-odbodbopenodbpyc) function is different from the [`session.openOdb`](https://help.3ds.com/2022/english/dssimulia_established/SIMACAEKERRefMap/simaker-c-odbopenodbcommandpyc.htm?contextscope=all&id=d16c67175beb4d0aa7584a7d4f2bfd5a#simaker-odbodbsesopenodbpyc).
> 
> The `odbAccess.openOdb` function can be run regardless of Abaqus CAE. See, for instance [this example](https://help.3ds.com/2022/english/dssimulia_established/SIMACAECMDRefMap/simacmd-c-odbintrosimpleexapyc.htm?contextscope=all&id=f32d4a1eda50408b96561de06760f215). Its usage is simply `abaqus python odbRead.py`, so I think that the command in this function could be changed to the following:
> 
> ```python
> os.system(f"{abaqus} python {filePath}")
> ```
> 
> What do you think?
> 
> In this way, the script doesn't use the Abaqus CAE kernel, which I think is the reason of two different functions with the same name.
> 
> _Originally posted by @Diogo-Rossi in [#1104 (comment)](https://github.com/haiiliin/abqpy/pull/1104#issuecomment-1240309844)_
> 
> ### Issue
> What if I want to run the script in `GUI` mode when `odbAccess.openOdb` is used and also includes the `import abaqus`, because the `abaqus` module can't be imported in `noGUI` mode, in this condition, an `ImportError` will be raised:
> 
> ```python
> > abaqus python
> ...
> >>> import odbAccess
> >>> from abaqus import *
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "SMAPython\SMAPytLibPy.m\src\site.py", line 120, in _numpyHook
>   File "SMAPyaModules\SMAPyaAbqPy.m\src\abaqus.py", line 16, in <module>
> ImportError: abaqus module may only be imported in the Abaqus kernel process
> ```

I think this still needs to be considered.

**Comment by haiiliin** [comment]
> > > What if I want to run the script in `GUI` mode when `odbAccess.openOdb` is used and also includes the `import abaqus`, because the `abaqus` module can't be imported in `noGUI` mode, in this condition, an `ImportError` will be raised:
> > > ```python
> > > > abaqus python
> > > ...
> > > >>> import odbAccess
> > > >>> from abaqus import *
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "SMAPython\SMAPytLibPy.m\src\site.py", line 120, in _numpyHook
> > >   File "SMAPyaModules\SMAPyaAbqPy.m\src\abaqus.py", line 16, in <module>
> > > ImportError: abaqus module may only be imported in the Abaqus kernel process
> > > ```
> > 
> > Yes, I think that is expected. `abaqus` module can only be imported with `abaqus cae` command (in both modes `noGUI` and without `noGUI`). This module can't be imported in with `abaqus python` command.
> > 
> > I think the purpose of using `odbAccess.openOdb` is to access ODB file without `abaqus cae` command (i.e. not importing `abaqus` module, if done, will raise the `Abaqus kernel` error message). That is the reason I thought it would use `abaqus python` command.
> > 
> > That is what I conclude from the [documentation](https://help.3ds.com/2022/English/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-odbopenodbcommandpyc.htm?contextscope=all&id=9f0ec3921d15431997232cb3f25d285d#simaker-odbodbopenodbpyc) when it says
> > 
> > > This method opens an existing output database (.odb) file and creates a new Odb object. You typically execute this method outside of Abaqus/CAE when, in most cases, only one output database is open at any time. For example,
> > 
> > For the situation of using Abaqus CAE, I think we can use the `session.openOdb`.
> > 
> > Do you have an example of using `odbAccess.openOdb` with `abaqus cae`?
> 
> How about just change the `session.openOdb` to `odbAccess.opdnOdb`:
> ```python
> from abaqus import *
> from abaqusConstants import *
> from driverUtils import *
> import odbAccess
> import numpy as np
> 
> executeOnCaeStartup()
> 
> # Open output database
> odb = odbAccess.openOdb('Job-1.odb')
> 
> o = session.odbs['Job-1.odb']
> session.viewports['Viewport: 1'].setValues(displayedObject=o)
> 
> # Extract output data
> dataList = session.xyDataListFromField(odb=odb, outputPosition=NODAL,
>                                        variable=(('U', NODAL, ((COMPONENT, 'U3'),)),),
>                                        nodeSets=('INSTANCE.SET-TOP', ))
> data = np.array(dataList[0])
> np.savetxt('data.csv', data, header='time,U3', delimiter=',', comments='')
> ```

I mean something like this.

**Comment by Diogo-Rossi** [comment]
> I mean something like this.

Ok, but I could not find a usage like that in the documentation.

> does not require to check the "cae" license.

I think this could lead to improve the usability.

**Comment by haiiliin** [comment]
I think it is totally reasoable, `odbAcces.openOdb` is just a function to oen the odb file, why can't I use sonething like this?

**Comment by Diogo-Rossi** [comment]
> I think it is totally reasonable, `odbAcces.openOdb` is just a function to open the odb file, why can't I use something like this? And it works in GUI mode.

Yes, that is totally reasonable. But you could use `session.openOdb` to do the same in this case, with identical result, I think. 

Everything that works in `abaqus python` CLI also seems to work in GUI mode (except for the function `help()`, I don't know why) but the reverse is not true.

I've thought that the purpose of using `odbAcces` was to avoid CAE, because I didn't find a example in the documentation with `odbAcces`  together with `import abaqus`.

But, if we really decide to remove this implementation, let's at least provide a CLI argument in the [Command Line feature](#1269) (let's say `-noCAE`) to allow execute `abaqus python script.py`. That would be useful in some cases.

**Comment by haiiliin** [comment]
The thing is, if the script runs OK in Abaqus/CAE, it shoud also be OK when running by `abqpy` by default, otherwise it would make the users very confused, most of the users will run the script in Abaqus/CAE.

**Comment by Diogo-Rossi** [comment]
Ok, no problem, but look:
If the users try to run [this example](https://help.3ds.com/2022/English/DSSIMULIA_Established/SIMACAECMDRefMap/simacmd-c-odbintroreadnodepyc.htm?contextscope=all&id=1344fa8ad4fa478b915eb336484f886f) directly with `abaqus cae` (with `abqpy`), it will not run OK.
They will have to modify the code to not get an error.

Besides, that example and also [this other example](https://help.3ds.com/2022/English/DSSIMULIA_Established/SIMACAECMDRefMap/simacmd-c-odbintrosimpleexapyc.htm?contextscope=all&id=f32d4a1eda50408b96561de06760f215) prints information to the terminal.
But if the users run these examples in `abaqus cae`, they will get no printing, because CAE does not print to the terminal.

**Comment by haiiliin** [comment]
OK, this seems reasonable enough, let's keep it this way.

**Comment by Diogo-Rossi** [comment]
But you still think that we should remove this feature from `odbAcces`, we could at least create that CLI option like:
```
abqpy -noCAE scripty.py
```
which may call `abaqus python` instead of `abaqus cae`

**Comment by haiiliin** [comment]
I have changed my mind, you re right about this, it should be clear that `odbAccess` will only suggested to be used outside abaqus kernel. Maybe we need to add something about this in the documentation.
