### ISSUE TITLE
Help on using side1Faces or side2Faces

### ISSUE THREAD

**Issue by QiangF** [haiiliin/abqpy#1402]
I am trying to model the rolling of metal bars with different groove shapes. The model has contact between roll surface and billet surface. In the snippet below, sometimes the roll surface is side1Face, sometimes is side2Face, how to know in advance which type of surface to select?

    f = roll.faces
    if groove_type == 'ovp':
        roll.Surface(side1Faces=f, name='ROLL')
    else:
        roll.Surface(side2Faces=f, name='ROLL')

**Comment by haiiliin** [comment]
I am not really familar with your condition, but you may check some information on [Part.Surface](https://abqpy.com/en/latest/reference/mdb/model/part.html?highlight=Surface#abaqus.Part.Part.Part.Surface).

**Comment by haiiliin** [comment]
I have no idea of a Surface having two side, in my own experience, I always use the `side1Faces`.

**Comment by haiiliin** [comment]
> I am trying to model the rolling of metal bars with different groove shapes. The model has contact between roll surface and billet surface. In the snippet below, sometimes the roll surface is side1Face, sometimes is side2Face, how to know in advance which type of surface to select?
> 
> ```
> f = roll.faces
> if groove_type == 'ovp':
>     roll.Surface(side1Faces=f, name='ROLL')
> else:
>     roll.Surface(side2Faces=f, name='ROLL')
> ```

What is the difference in the created abaqus model using the two different arguments?

**Comment by QiangF** [comment]
These two options result in surface selection on the opposite side of the shell of the roll.
![img_2022_09_15__22_03_36](https://user-images.githubusercontent.com/8192731/190567915-164298e5-48ed-4a5b-8daf-5876f7c40f64.png)

**Comment by haiiliin** [comment]
Maybe here is some information you can refer to: https://help.3ds.com/2021/english/dssimulia_established/simacaecaerefmap/simacae-c-picconcside.htm?contextscope=cloud.

**Comment by haiiliin** [comment]
It seems that `side1Faces` depends on the previous selection, if you use `side2Faces` to create a Surface once, the next time if you still use `side2Faces` to create the surface, the created surface will be the opposite surface.

**Comment by haiiliin** [comment]
> It seems that whether it is `side1Faces` or `side2Faces` depends on the previous selections, if you use `side2Faces` to create a Surface once, the next time if you still use `side2Faces` to create the surface, the created surface will be the opposite surface.

I am not sure if it is correct.

**Comment by haiiliin** [comment]
Close this since it is off the topic.
