### ISSUE TITLE
issue in running `abaqus python` with `import odbAccess`

### ISSUE THREAD

**Issue by Diogo-Rossi** [haiiliin/abqpy#1549]
Since the `odbAccess` module imports names from `abaqus` module, the script always runs in `cae` mode, because `abaqus` module calls `run(cae=True)`. So, the line `run(cae=False)` is never executed.

### Possible solution

Move the line `abqpy.abaqus.run(cae=False)` to before importing `abaqus`.

Branch [issue-running-odbAccess-abaqus-python](https://github.com/haiiliin/abqpy/tree/issue-running-odbAccess-abaqus-python)

https://github.com/haiiliin/abqpy/blob/80d82bbc690741ecd699ad417846aa4dd8516bd8/src/odbAccess.py#L1-L8

Others solutions could be moving the call `run(cae=True)` to other module or function, like the function `executeOnCaeStartup()`

**Comment by haiiliin** [comment]
> https://github.com/haiiliin/abqpy/blob/80d82bbc690741ecd699ad417846aa4dd8516bd8/src/odbAccess.py#L1-L8

I think this is quite a good solution for this issue.
