### ISSUE TITLE
Suppress typing warnings

### ISSUE THREAD

**Issue by Diogo-Rossi** [haiiliin/abqpy#275]
Since some function files has only type hints, why not use stub `.pyi` for that files?

This could lead to 2 improvements:
* Differentiate files with code from that only with annotations 
* Suppress warnings when writing the type hints

BTW: Thank you for making this project.

**Comment by haiiliin** [comment]
@Diogo-Rossi Would you like to work on this?

**Comment by Diogo-Rossi** [comment]
> @Diogo-Rossi Would you like to work on this?

@haiiliin Sure, I will try to.
