### ISSUE TITLE
关于odb文件读取时，python 调试出错的问题。

### ISSUE THREAD

**Issue by xiaomaiAI** [haiiliin/abqpy#4204]
你好，本人Abaqus新人，有个问题咨询一下，我在使用abqpy读取odb文件时，遇到该问题： vscode中使用python run，一切正常，但是python debug会报错：无结果且属性类型和run结果也不一致。不太明白何原因导致该情况，再此请教一下。

**Comment by haiiliin** [comment]
因为 abqpy 只是简单调用 Abaqus 命令行运行当前脚本，调用命令行后程序会立刻退出安装了 abqpy 的当前 Python 解释器。

处于调试状态时，当前 Python 脚本不会提交给 Abaqus 运行，仅在安装了 abqpy 的 Python 解释器上运行，当前 abqpy 的很多函数都没有代码实现，因此很有可能运行出错。

对于一些简单的脚本，调试时可能可以在安装了 abqpy 的 Python 解释器上运行成功，这样可以通过调试大体查看 Abaqus 对象的基本结构。

总之，abqpy 目前还不支持调试功能，调试时 脚本不会提交给 Abaqus 运行，仅在安装了 abqpy 的 Python 解释器上运行。

**Comment by xiaomaiAI** [comment]
好的，谢谢你的解答。我之前是C++来调用这个python脚本，发现会出错（和调试的现象一致），现在在想解决办法

**Comment by haiiliin** [comment]
> 好的，谢谢你的解答。我之前是C++来调用这个python脚本，发现会出错（和调试的现象一致），现在在想解决办法

由于许可证的问题，我觉得想在 Abaqus/CAE 环境外调试 Python 脚本几乎不太可能，只能使用 Abaqus 官方的 Abaqus PDE。

**Comment by xiaomaiAI** [comment]
> > 好的，谢谢你的解答。我之前是C++来调用这个python脚本，发现会出错（和调试的现象一致），现在在想解决办法
> 
> 由于许可证的问题，我觉得想在 Abaqus/CAE 环境外调试 Python 脚本几乎不太可能，只能使用 Abaqus 官方的 Abaqus PDE。

收到，谢谢！
