### ISSUE TITLE
Functions InstanceFromBooleanCut and InstanceFromBooleanMerge shuld be under rootAssembly

### ISSUE THREAD

**Issue by cristobaltapia** [haiiliin/abqpy#4488]
**Describe the bug**
The functions `InstanceFromBooleanCut` and `InstanceFromBooleanMerge` should be under `rootAssembly`, but they are under `PartInstance`. Maybe my documentation is outdated, but in the documentation from V2020 it is stated that the path to these functions is `mdb.models[name].rootAssembly.InstanceFromBooleanCut`. This is also the path that I have always used, so I know it works.

**To Reproduce**

See definitions is: 
- https://github.com/haiiliin/abqpy/blob/34c38d6a4915f42984af2259836b32d47583923a/src/abaqus/Assembly/PartInstance.py#L229
- https://github.com/haiiliin/abqpy/blob/34c38d6a4915f42984af2259836b32d47583923a/src/abaqus/Assembly/PartInstance.py#L229

**Reproducible Code**

```python
from abaqus import *

model = mdb.Model(name="test")
asmb = model.rootAssembly
asmb.InstanceFromBooleanCut() # <- not working

inst = asmb.instances["some instance"].InstanceFromBooleanCut() # <- This works
```

**Expected behavior**
The autocompletion should work.

**Screenshots**
This shows how the function is not found under rootAssembly:
![Screenshot-2023-05-24-140647](https://github.com/haiiliin/abqpy/assets/7276493/63746f26-0b7f-45c0-b139-b609d295d5e6)

This shows how it is found under a PartInstance:
![Screenshot-2023-05-24-140625](https://github.com/haiiliin/abqpy/assets/7276493/1ce91d10-f833-412d-953b-e7f87a6e73a9)

**Additional context**
I am using this in neovim with lspconfig. This should not be relevant, however.

[edit:] By the way, thanks for the nice implementation of stubs. I had actually begun doing this myself a few days ago, until I found this repo. You saved me some work :P

**Comment by haiiliin** [comment]
Have you checked Abaqus 2023 documentation?

**Comment by haiiliin** [comment]
I think you are right, the docstrings show that they should be Assembly's methods

**Comment by haiiliin** [comment]
It seems that the Abaqus documentation put this methods in a wrong place

**Comment by cristobaltapia** [comment]
The Abaqus documentation for the python API is sometimes rather confusing I would say. :P

**Comment by haiiliin** [comment]
> The Abaqus documentation for the python API is sometimes rather confusing I would say. :P

haha, the documentation says it can be access by `mdb.models[name].rootAssembly.Instance` 😢

**Comment by haiiliin** [comment]
@cristobaltapia Can you check if it is working by installing the patch #4489:
`pip install git+https://github.com/haiiliin/abqpy@fix-assembly-instance`

**Comment by cristobaltapia** [comment]
Yes, that fixes the problem. Thanks for the quick response!

**Comment by haiiliin** [comment]
Great! I'm merging it.

**Comment by haiiliin** [comment]
New version `20**.5.2` has been published.
