### ISSUE TITLE
CircleByCenterPerimeter (ConstrainedSketchGeometry) is returning None

### ISSUE THREAD

**Issue by cristobaltapia** [haiiliin/abqpy#4522]
**Describe the bug**

The method `CircleByCenterPerimeter` defined in `ConstrainedSketchGeometry` is returning `None` instead of a `ConstrainedSketchGeometry`. I am not sure why this is happening. Maybe, instead of this being defined as a class, it should be defined as a method of `ConstrainedSketchGeometry`? Probably all the other methods from `ConstrainedSketchGeometry` are affected too, as they are defined in the same way (I haven't tested them though).

**To Reproduce**

1. Create a `ConstrainedSketch` object
2. Use the method `CircleByCenterPerimeter(...)`
3. The result is a `None`

**Reproducible Code**

```python
model = mdb.Model(name="test")
sk_1 = model.ConstrainedSketch(name="test sketch", sheetSize=2000.0)
c1 = sk_1.CircleByCenterPerimeter(center=(0.0, 10), point1=(0.0, 0.0))
```

**Expected behavior**

The method should return a `ConstrainedSketchGeometry` object.

**Screenshots**

This is the hover over the method `CircleByCenterPerimeter`, where it can be seen that it returns a `None` (`-> None`)
![Screenshot-2023-05-26-145122](https://github.com/haiiliin/abqpy/assets/7276493/6c2b4bdb-3e2c-4451-9cfd-dc65b2ffe04f)

This is the type of the result variable `C1`:
![Screenshot-2023-05-26-145147](https://github.com/haiiliin/abqpy/assets/7276493/f9725aef-9597-4c55-9d6d-502fff646f2d)

**Comment by haiiliin** [comment]
It is a bug, other methods in ConstrainedSketch should also return the created geometry objects instead of None

**Comment by cristobaltapia** [comment]
Thanks for the fix!
