### ISSUE TITLE
fail to call abaqus in abdpy after installing it

### ISSUE THREAD

**Issue by ZPLai** [haiiliin/abqpy#4605]
Dear @haiiliin ,
thanks very much for developing such wonderful tool.
I think it could help me and others for efficient using of abaqus in python.
Now I have a very fundamental problem.
I have an **abaqus-2023** in my computer, which can successfully work for simulation. And I create an env by using anoconda, and install abqpy in this env by using **pip install abqpy==2023.*** and I also install jupyter notebook in same env.
However, when I run the exmaples you provide, abqpy2023 seems not work. 

For instance, when runing "**compression.py**" and "**compression_output.py**". The "**data**" is empty.
and when runing "**skewExample.py**“, I obtain following **error messages**:
"_KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_3016/1622241201.py in <module>
    263 
    264 model = mdb.models["Model-1"]
--> 265 part = model.parts["Plate"]
    266 feature = part.features["Shell planar-1"]
    267 assembly = model.rootAssembly

KeyError: 'Plate'_"

It seems I did not rightly set up the abqpy in my computer. do you have any advices for me? And anybody have similar issues?

**Comment by haiiliin** [comment]
Will you try running the example with the `abaqus` command directly, i.e.,
```sh
abaqus cae noGUI=compression.py
abaqus cae noGUI=compression-output.py
```

**Comment by ZPLai** [comment]
> 

I can run the example by abaqus command successfully, and obtain a dada.csv file with corresponding results in it.

**Comment by ZPLai** [comment]
> > 
> 
> I can run the example by abaqus command successfully, and obtain a dada.csv file with corresponding results in it.



> Will you try running the example with the `abaqus` command directly, i.e.,
> 
> ```shell
> abaqus cae noGUI=compression.py
> abaqus cae noGUI=compression-output.py
> ```


I can run the example by abaqus command successfully, and obtain a dada.csv file with corresponding results in it.

**Comment by haiiliin** [comment]
You mean you can't get expected results by running the script directly with python?

**Comment by ZPLai** [comment]
> You mean you can't get expected results by running the script directly with python?

yes. when I run compression.py、compression-output.py using abqpy, the code complete very quickly, which seems no-call on abaqus for real simulation. And the genered data.csv is also empty without any data (only table tile exists)

**Comment by ZPLai** [comment]
> You mean you can't get expected results by running the script directly with python?

And also, when I run "skewExample.py“, following error message occurs:
"_KeyError Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_3016/1622241201.py in
263
264 model = mdb.models["Model-1"]
--> 265 part = model.parts["Plate"]
266 feature = part.features["Shell planar-1"]
267 assembly = model.rootAssembly

KeyError: 'Plate'_"
It is very strange.

**Comment by haiiliin** [comment]
Can you take a screenshot of the terminal when you run the script? Normally it is like this, the command used to submit the script will be shown.
![image](https://github.com/haiiliin/abqpy/assets/47051427/167622c8-dd1b-4d69-9857-1da0691fcd16)

**Comment by haiiliin** [comment]
> > You mean you can't get expected results by running the script directly with python?
> 
> And also, when I run "skewExample.py“, following error message occurs: "_KeyError Traceback (most recent call last) ~\AppData\Local\Temp/ipykernel_3016/1622241201.py in 263 264 model = mdb.models["Model-1"] --> 265 part = model.parts["Plate"] 266 feature = part.features["Shell planar-1"] 267 assembly = model.rootAssembly
> 
> KeyError: 'Plate'_" It is very strange.

There are some problems in `skewExample`, you have to generate the `skew.cae` file in the script like this:
https://github.com/haiiliin/abqpy/blob/3c26d4e93e692cbe4ee81239d69a12dcb335e143/examples/Abaqus/skewExample.py#L240-L258

**Comment by ZPLai** [comment]
> Can you take a screenshot of the terminal when you run the script? Normally it is like this, the command used to submit the script will be shown. ![image](https://user-images.githubusercontent.com/47051427/247525422-167622c8-dd1b-4d69-9857-1da0691fcd16.png)
I have following meaasages, when submiting the code by commands.
![@@THZHGN%%CI K@2KERPCBH](https://github.com/haiiliin/abqpy/assets/17693587/e45bfe5a-02e1-4f23-a619-028fe1337090)

**Comment by haiiliin** [comment]
In the output script, the `Job-1.odb` is opened, can you check if `Job-1.odb` exists in the current work directory? In your case, `C\Users\admin\Job-1.odb`.
![image](https://github.com/haiiliin/abqpy/assets/47051427/222038ee-3f4f-4143-a085-3b663df9552d)

**Comment by ZPLai** [comment]
> In the output script, the `Job-1.odb` is opened, can you check if `Job-1.odb` exists in the current work directory? In your case, `C\Users\admin\Job-1.odb`. ![image](https://user-images.githubusercontent.com/47051427/247530352-222038ee-3f4f-4143-a085-3b663df9552d.png)

Amazing!
I found this odb file, and also, I found a data.csv file, with right results.
It is very strange. I try to run the code in jupyter notebook again, still cannot obtain right data.csv. But using command-line can give me right results.
Do you have any idea about that?

**Comment by ZPLai** [comment]
> > In the output script, the `Job-1.odb` is opened, can you check if `Job-1.odb` exists in the current work directory? In your case, `C\Users\admin\Job-1.odb`. ![image](https://user-images.githubusercontent.com/47051427/247530352-222038ee-3f4f-4143-a085-3b663df9552d.png)
> 
> Amazing! I found this odb file, and also, I found a data.csv file, with right results. It is very strange. I try to run the code in jupyter notebook again, still cannot obtain right data.csv. But using command-line can give me right results. Do you have any idea about that?

seems the jupyter notebook did not rightly call abaqus, BUT in command line, the python can call abaqus rightly.

**Comment by haiiliin** [comment]
You may need to install the `ipynbname` and `nbconvert` package to get the Jupyter to be worked:
```sh
pip install ipynbname nbconvert
```
The `abqpy` package uses `ipynbname` to get the name of the notebook and use `nbconvert` to convert the notebook to a plain Python file.

You can check if a Python file with the same name as the Jupyter Notebook exists in the working directory when using Jupyter Notebook.

**Comment by ZPLai** [comment]
> You may need to install the `ipynbname` and `nbconvert` package to get the Jupyter to be worked:
> 
> ```shell
> pip install ipynbname nbconvert
> ```
> 
> The `abqpy` package uses `ipynbname` to get the name of the notebook and use `nbconvert` to convert the notebook to a plain Python file.
> 
> You can check if a Python file with the same name as the Jupyter Notebook exists in the working directory when using Jupyter Notebook.

I just copy the code into jupyter notebook, while not noting the file name. So the file name is similar to untitled.ipynb.
Seems this could be the problem. I'll try your solution latter. 

Thanks very much for such nice and patient and quick response!
And thanks for very useful abqpy!

**Comment by ZPLai** [comment]
> You may need to install the `ipynbname` and `nbconvert` package to get the Jupyter to be worked:
> 
> ```shell
> pip install ipynbname nbconvert
> ```
> 
> The `abqpy` package uses `ipynbname` to get the name of the notebook and use `nbconvert` to convert the notebook to a plain Python file.
> 
> You can check if a Python file with the same name as the Jupyter Notebook exists in the working directory when using Jupyter Notebook.







I install the packages as you mentioned "pip install ipynbname nbconvert".
After that, I try "compression"code in jupyter notebook again, and I obtain following messages:
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Running the following command: abaqus cae noGUI=C:\Users\admin\Desktop\abqpy-2023\examples\Compression\compression.py -- -f C:\Users\admin\AppData\Roaming\jupyter\runtime\kernel-03fa7225-ddd5-4986-a304-5022e3feb9c8.json
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
An exception has occurred, use %tb to see the full traceback.

SystemExit: 0


%tb
SystemExit                                Traceback (most recent call last)
Cell In[3], line 14
      1 """
      2 Compression Model
      3 =================
   (...)
     11     A simple compression model.
     12 """
---> 14 from abaqus import *
     15 from abaqusConstants import *
     16 from caeModules import *

File c:\Users\admin\anaconda3\envs\abqpy2023\Lib\site-packages\abaqus\__init__.py:26
     23 YES = abaqusConstants.YES
     24 NO = abaqusConstants.NO
---> 26 run(cae=True)
     28 __main__ = sys.modules["__main__"]

File c:\Users\admin\anaconda3\envs\abqpy2023\Lib\site-packages\abqpy\run.py:55, in run(cae)
     53 else:
     54     abaqus.python(filePath, *sys.argv[1:], **options)
---> 55 sys.exit(0)

SystemExit: 0

​

**Comment by haiiliin** [comment]
This is expected, the script should be submitted to abaqus, the local python interpreter is then terminated.

**Comment by ZPLai** [comment]
> This is expected, the script should be submitted to abaqus, the local python interpreter is then terminated.

BUT the jupyter notebook was installed at same env as that of abqpy. In my opinion, they show call the python interpreter at same env, which could support abaqus-calling?

**Comment by ZPLai** [comment]
> This is expected, the script should be submitted to abaqus, the local python interpreter is then terminated.

And I have tried Pycharm to run the compression.py, by using the python interpreter in same env (named as abqpy2023). I found that works. And in fact, I should delete the code of "job.submit()". Otherwise, the code can not be succesfully run in Pycharm.

**Comment by ZPLai** [comment]
> > This is expected, the script should be submitted to abaqus, the local python interpreter is then terminated.
> 
> And I have tried Pycharm to run the compression.py, by using the python interpreter in same env (named as abqpy2023). I found that works. And in fact, I should delete the code of "job.submit()". Otherwise, the code can not be succesfully run in Pycharm.

with following meassages:
C:\Users\admin\anaconda3\envs\abqpy2023\python.exe C:\Users\admin\Desktop\abqpy-2023\examples\Compression\compression2.py 
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

---------------------------------------------------------------
Running the following command: abaqus cae noGUI=compression2.py
---------------------------------------------------------------
Abaqus License Manager checked out the following license:
"cae" from Flexnet server whmfc
<9998 out of 9999 licenses remain available>.
WindowsError: [Error 2]
File "compression2.py", line 89, in <module>
    job.submit()

Abaqus Error: cae exited with an error.

Process finished with exit code 0

**Comment by haiiliin** [comment]
The python interpreter where abqpy is installed is just meant to do the type checking and use the command line to call the abqus command, the abaqus command will call the abaqus internal python interpreter to run the script.

After calling the abaqus command, the python interpreter where abqpy is installed will be terminated because abqpy is only for type checking and running the script does not do anything.

**Comment by haiiliin** [comment]
The only difference between running a plain python file or a jupyter notebook is  that the notebook will be converted to a plain python file and then been submitted to abaqus. The python interpreter where abqpy is installed will be terminated either way.

**Comment by ZPLai** [comment]
> The python interpreter where abqpy is installed is just meant to do the type checking and use the command line to call the abqus command, the abaqus command will call the abaqus internal python interpreter to run the script.
> 
> After calling the abaqus command, the python interpreter where abqpy is installed will be terminated because abqpy is only for type checking and running the script does not do anything.

I understand your words. I konw that the python interpreter is just to do the task of preparing the script for modeling, while the real modeling and simulation are conducted by abaqus and its internal python.

And herein, I used jupyter or pycharm is just as a typing tool. What confused me is that I cannot submit the task directly in jupyter, as I faced above mentioned error messages.

**Comment by haiiliin** [comment]
> > This is expected, the script should be submitted to abaqus, the local python interpreter is then terminated.
> 
> And I have tried Pycharm to run the compression.py, by using the python interpreter in same env (named as abqpy2023). I found that works. And in fact, I should delete the code of "job.submit()". Otherwise, the code can not be succesfully run in Pycharm.

`job.submit()` should work, just wait for some seconds, the job is running..

**Comment by ZPLai** [comment]
> > > This is expected, the script should be submitted to abaqus, the local python interpreter is then terminated.
> > 
> > 
> > And I have tried Pycharm to run the compression.py, by using the python interpreter in same env (named as abqpy2023). I found that works. And in fact, I should delete the code of "job.submit()". Otherwise, the code can not be succesfully run in Pycharm.
> 
> `job.submit()` should work, just wait for some seconds, the job is running..

it remind me that CAE exited with an error. And I did not see a right data.csv file as expected.
BUT If I deleted this words, the code can rightly work

**Comment by haiiliin** [comment]
The SystemExit(0) exception in Jupyter notebook is expected, here it means the script has been successfully submitted to abaqus.

**Comment by haiiliin** [comment]
> > > > This is expected, the script should be submitted to abaqus, the local python interpreter is then terminated.
> > > 
> > > 
> > > And I have tried Pycharm to run the compression.py, by using the python interpreter in same env (named as abqpy2023). I found that works. And in fact, I should delete the code of "job.submit()". Otherwise, the code can not be succesfully run in Pycharm.
> > 
> > `job.submit()` should work, just wait for some seconds, the job is running..
> 
> it remind me that CAE exited with an error. And I did not see a right data.csv file as expected.
> BUT If I deleted this words, the code can rightly work 

Do you combine two scripts into one notebook?

**Comment by ZPLai** [comment]
> > > > > This is expected, the script should be submitted to abaqus, the local python interpreter is then terminated.
> > > > 
> > > > 
> > > > And I have tried Pycharm to run the compression.py, by using the python interpreter in same env (named as abqpy2023). I found that works. And in fact, I should delete the code of "job.submit()". Otherwise, the code can not be succesfully run in Pycharm.
> > > 
> > > 
> > > `job.submit()` should work, just wait for some seconds, the job is running..
> > 
> > 
> > it remind me that CAE exited with an error. And I did not see a right data.csv file as expected.
> > BUT If I deleted this words, the code can rightly work
> 
> Do you combine two scripts into one notebook?

Yes. I combine them together, and run it in pycharm.
IN pycharm I have succeeed. BUT in jupyter, I have never succeed.

**Comment by ZPLai** [comment]
> 



> > > > > > This is expected, the script should be submitted to abaqus, the local python interpreter is then terminated.
> > > > > 
> > > > > 
> > > > > And I have tried Pycharm to run the compression.py, by using the python interpreter in same env (named as abqpy2023). I found that works. And in fact, I should delete the code of "job.submit()". Otherwise, the code can not be succesfully run in Pycharm.
> > > > 
> > > > 
> > > > `job.submit()` should work, just wait for some seconds, the job is running..
> > > 
> > > 
> > > it remind me that CAE exited with an error. And I did not see a right data.csv file as expected.
> > > BUT If I deleted this words, the code can rightly work
> > 
> > 
> > Do you combine two scripts into one notebook?
> 
> Yes. I combine them together, and run it in pycharm. IN pycharm I have succeeed. BUT in jupyter, I have never succeed.

And I just try again. in only one script, same thing happen again. seems job.submit() should be deleted.

**Comment by haiiliin** [comment]
You should not. There should be two individual abaqus commands to build the model and getting the output. But python the file always runs the whole script

**Comment by haiiliin** [comment]
When you keep `job.submit`, the job is not processing?

**Comment by ZPLai** [comment]
> 



> When you keep `job.submit`, the job is not processing?

Yes. Keep job.submit, the job is not processing

**Comment by haiiliin** [comment]
> > 
> 
> 
> 
> > When you keep `job.submit`, the job is not processing?
> 
> Yes. Keep job.submit, the job is not processing

The submitted abaqus command displays on the console?

**Comment by ZPLai** [comment]
In fact, I notice abqpy, because I need using tensorflow, pytorch, as well as lots of other machine learning package to support my modeling with abaqus.
I thought the abqpy could help me realize my work.
BUT I'm not sure. So, I want to check if I have correctly understanding the development motivation of ABQPY. If it could help the ABQUS user to freely access the diverse python tool without the limitation by the internal abaqus-python?

**Comment by ZPLai** [comment]
> In fact, I notice abqpy, because I need using tensorflow, pytorch, as well as lots of other machine learning package to support my modeling with abaqus. I thought the abqpy could help me realize my work. BUT I'm not sure. So, I want to check if I have correctly understanding the development motivation of ABQPY. If it could help the ABQUS user to freely access the diverse python tool without the limitation by the internal abaqus-python?

And NOW, I have figured out at least one reliable approach to using PYTHON-3.11 to co-work with abaqus, that is, submiting the script by using "python -u ****.py". It does work. Jupyter and pycharm seem not work now.

I wonder if I pip tensoflow package in same env of Abqpy, can I use Tensorflow in the script? It may help me combination FEM and Machine learning, two of them may be inteacted with each other in loop.

**Comment by haiiliin** [comment]
> In fact, I notice abqpy, because I need using tensorflow, pytorch, as well as lots of other machine learning package to support my modeling with abaqus.
> I thought the abqpy could help me realize my work.
> BUT I'm not sure. So, I want to check if I have correctly understanding the development motivation of ABQPY. If it could help the ABQUS user to freely access the diverse python tool without the limitation by the internal abaqus-python?

I think the abaqus command is the only way to interact abaqus kernal outside abaqus/cae, abqpy just provides a convinent way to call the command. Other than this, abqpy is nothing but a type checker with code completions.

**Comment by ZPLai** [comment]
> > In fact, I notice abqpy, because I need using tensorflow, pytorch, as well as lots of other machine learning package to support my modeling with abaqus.
> > I thought the abqpy could help me realize my work.
> > BUT I'm not sure. So, I want to check if I have correctly understanding the development motivation of ABQPY. If it could help the ABQUS user to freely access the diverse python tool without the limitation by the internal abaqus-python?
> 
> I think the abaqus command is the only way to interact abaqus kernal outside abaqus/cae, abqpy just provides a convinent way to call tjw command. Other than this, abqpy is nothing but a type checker with code completions.

SO, if I pip lots of other packages, such as tensorflow in same env, can I use them with abqpy together. For instance, I may use a function in tensorflow to calculate the pressure loading that shall be used in abaqus. Can I realize that by combining abqpy with tensorflow?

**Comment by ZPLai** [comment]
In fact, I'm not very familiar with both abaqus and python both. So my question may seems strange to some degree

**Comment by haiiliin** [comment]
> > > In fact, I notice abqpy, because I need using tensorflow, pytorch, as well as lots of other machine learning package to support my modeling with abaqus.
> > > I thought the abqpy could help me realize my work.
> > > BUT I'm not sure. So, I want to check if I have correctly understanding the development motivation of ABQPY. If it could help the ABQUS user to freely access the diverse python tool without the limitation by the internal abaqus-python?
> > 
> > I think the abaqus command is the only way to interact abaqus kernal outside abaqus/cae, abqpy just provides a convinent way to call tjw command. Other than this, abqpy is nothing but a type checker with code completions.
> 
> SO, if I pip lots of other packages, such as tensorflow in same env, can I use them with abqpy together. For instance, I may use a function in tensorflow to calculate the pressure loading that shall be used in abaqus. Can I realize that by combining abqpy with tensorflow?

See here for an example

https://abqpy.readthedocs.io/en/stable/examples/Parameter-Identification/optimize.html#sphx-glr-examples-parameter-identification-optimize-py

The scripts are here

https://github.com/haiiliin/abqpy/tree/2023/examples/Parameter-Identification

**Comment by ZPLai** [comment]
I seems understand now.

In abqpy, running the code "XXX.py" (with "from abaqus import *"), is equal to submit a command line as "abaqus cae noGUI=XXX.py"?
So the XXX.py should not have any modules that not exist in internal python intepreter of abaqus? For instance, tensorflow? Even I pip tensorflow in abqpy env, I still should not use it in XXX.py code? Since the internal python intepreter can not recognize it?
And if I want to use Tensorflow (or pandas as you use in optimize.py), I should build another script and use tensorflow or pandas in this script, while calling XXX.py by using os.system command?

MY understanding is right or not?

**Comment by haiiliin** [comment]
> I seems understand now.
> 
> In abqpy, running the code "XXX.py" (with "from abaqus import *"), is equal to submit a command line as "abaqus cae noGUI=XXX.py"?
> So the XXX.py should not have any modules that not exist in internal python intepreter of abaqus? For instance, tensorflow? Even I pip tensorflow in abqpy env, I still should not use it in XXX.py code? Since the internal python intepreter can not recognize it?
> And if I want to use Tensorflow (or pandas as you use in optimize.py), I should build another script and use tensorflow or pandas in this script, while calling XXX.py by using os.system command?
> 
> MY understanding is right or not?

Right

**Comment by ZPLai** [comment]
> 
THat's great! 

So, following two scripts would be nearly equal to each others?
1.  os.system(f"python ../compression.py")
2.  os.system('abaqus cae noGUI=compression.py')

BUT script 2 seems not neccessry to depend on abqpy?
I can use it in any python version to call abqus to run "compression"?
Is it right?

**Comment by haiiliin** [comment]
> > 
> THat's great! 
> 
> So, following two scripts would be nearly equal to each others?
> 1.  os.system(f"python ../compression.py")
> 2.  os.system('abaqus cae noGUI=compression.py')
> 
> BUT script 2 seems not neccessry to depend on abqpy?
> I can use it in any python version to call abqus to run "compression"?
> Is it right?

Right

**Comment by ZPLai** [comment]
> > > 
> > 
> > 
> > THat's great!
> > So, following two scripts would be nearly equal to each others?
> > 
> > 1. os.system(f"python ../compression.py")
> > 2. os.system('abaqus cae noGUI=compression.py')
> > 
> > BUT script 2 seems not neccessry to depend on abqpy?
> > I can use it in any python version to call abqus to run "compression"?
> > Is it right?
> 
> Right


I got it! Thanks very much!

**Comment by haiiliin** [comment]
> I got it! Thanks very much!

Happy to help

**Comment by diogo-rossi** [comment]
Hello @ZPLai 

> In abqpy, running the code "XXX.py" (with "from abaqus import *"), is equal to submit a command line as "abaqus cae noGUI=XXX.py"? So the XXX.py should not have any modules that not exist in internal python intepreter of abaqus? For instance, tensorflow? Even I pip tensorflow in abqpy env, I still should not use it in XXX.py code? Since the internal python intepreter can not recognize it? And if I want to use Tensorflow (or pandas as you use in optimize.py), I should build another script and use tensorflow or pandas in this script, while calling XXX.py by using os.system command?

You were correct.

In general, you have a **Python 3.x** interpreter with all your environment (`tensorflow`, `pandas`, `pytorch`, etc... AND `abqpy`).

You can then write scripts with the type hints provided by `abqpy`. Your editor will recognize the type hints for Abaqus modules, and the **type checker** should run ok.

However, when using Abaqus modules, your script will not run in your environment, but on the **Abaqus Python Environment** (another environment) which does not have the same modules and packages as your Python 3 environment and also, prior to 2024, did not have even the same python interpreter version (Abaqus used Python 2.7 back then).

However, it now may have changed...

Abaqus 2024 uses a Python 3.10 interpreter and it may be possible to [install modern packages in its environment](https://tecnodigitalschool.com/how-to-install-python-packages-in-abaqus/).

I did not fully tested that yet, but it may work.

With this, I think you can use only one script that runs on Abaqus Python Environment with all new installed packages.
