### ISSUE TITLE
"connectorBehavior" is not recognized.

### ISSUE THREAD

**Issue by lizhoukan1** [haiiliin/abqpy#4673]
**Describe the bug**
With the version of abqpy which I am using (2023.5.3), the Abaqus built-in module "connectorBehavior" is not recognized. In VS Code, when this word is used, it tells that " 'connectorBehavior' is not defined.

**To Reproduce**
(As shown in the following code and the screenshot)

**Reproducible Code**

model = mdb.models['Model-1']
model.ConnectorSection(name='longitudinal_column_sliding', 
    translationalType=CARTESIAN, rotationalType=ALIGN)
elastic_0 = connectorBehavior.ConnectorElasticity(components=(1, 2, 3), table=((
    50000.0, 50000.0, 50000.0), ))
model.sections['longitudinal_column_sliding'].setValues(
    behaviorOptions = (elastic_0, ) )
model.sections['longitudinal_column_sliding'].behaviorOptions[0].ConnectorOptions()

**Expected behavior**
The "connectorBehavior" will be recognized and is not regarded as something undefined.

**Screenshots**
![image](https://github.com/haiiliin/abqpy/assets/32449835/5fa7b5c8-a099-4adb-a082-272e2e271a98)

**Additional context**
Not applicable.

**Comment by haiiliin** [comment]
Did you import connectorBehavior? It seems that the module is indeed included in the package.

**Comment by haiiliin** [comment]
Maybe it is because the module is imported by other modules in abaqus automatically, however we didn't know it in abqpy.

**Comment by lizhoukan1** [comment]
> Maybe it is because the module is imported by other modules in abaqus automatically, however we didn't know it in abqpy.



> Did you import connectorBehavior? It seems that the module is indeed included in the package.

Thank you for your reply. As suggested, I imported connectorBehavior directly and the warning messages disappeared, as shown below:
![image](https://github.com/haiiliin/abqpy/assets/32449835/da6dbaec-221e-4529-a6ae-64fba5b2214f)
![image](https://github.com/haiiliin/abqpy/assets/32449835/f5122495-4057-4c4f-a4d5-b9fd3c407a96)
Without "import connectorBehavior", the messages will emerge again:
![image](https://github.com/haiiliin/abqpy/assets/32449835/94964a98-308b-4338-b8b8-a37e12d62274)



In Abaqus itself, this module is imported in caeModules, as shown in the following screenshot. However, although caeModules was also imported in the code as in the previous screenshot, connectorBehavior was not recognized.
![image](https://github.com/haiiliin/abqpy/assets/32449835/6ffe84c4-1581-4559-863d-835d45562d96)

**Comment by haiiliin** [comment]
New version 20**.5.4 have been published with patch #4682.
