### ISSUE TITLE
AttributeError: 'module' object has no attribute 'LeafFromElementSets'

### ISSUE THREAD

**Issue by keblicuey** [haiiliin/abqpy#4903]
**Describe the bug**
With the version of abqpy which I am using (2023.5.5), when using LeafFromElementSets in pycharm, it tells that "AttributeError: 'module' object has no attribute 'LeafFromElementSets'".  I used pythonreader to get the command of creating displaygroup. however, it doesn't work when I try to run the command. 
And in [SIMULIA User Assistance 2023](https://help.3ds.com/2023/English/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-leaffromelementsetspyc.htm?contextscope=all&id=479527b4dee54fea9fb2752679a091d7#simaker-c-leaffromelementsetspyc__simaker-c-leaffromelementsetspyc-s-pyaccess1), it tells that "import displayGroupOdbToolset", actually the object is in displayGroupMdbToolset using abqpy.

**Reproducible Code**

```python
from abaqus import *
from abaqusConstants import *
from caeModules import *
for i in range(1, 51, 1):
    obj = session.openOdb(name='C:/abaqus_practice/tsjam/test1/2-1/2-1-4/results/Job-' + str(i) + '.odb')
    session.viewports['Viewport: 1'].setValues(displayedObject=obj)
    session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(CONTOURS_ON_DEF, ))
    leaf = dgm.LeafFromElementSets(elementSets=("BASE-1.BASE_FACE1",))
    dg = session.DisplayGroup(leaf=leaf, name='base_surface_top')
    dg1 = session.displayGroups['base_surface_top']
    session.viewports['Viewport: 1'].odbDisplay.setValues(visibleDisplayGroups=(dg1,))
    session.writeOBJFile(fileName='C:/abaqus_practice/tsjam/test1/2-1/2-1-4/surfaces/top/sf' + str(i) + '.obj',
                         canvasObjects=(session.viewports['Viewport: 1'], ))
```

**Comment by keblicuey** [comment]
![屏幕截图 2023-08-21 210904](https://github.com/haiiliin/abqpy/assets/81084513/4335264d-c89f-4c14-84c5-0b7a4ab0b372)
![屏幕截图 2023-08-21 211326](https://github.com/haiiliin/abqpy/assets/81084513/37599ca7-cace-48c5-9647-73a79b64f458)

**Comment by keblicuey** [comment]
Commands read by PythonReader
![屏幕截图 2023-08-21 212229](https://github.com/haiiliin/abqpy/assets/81084513/e33586b3-02a0-4bd3-9567-8ce81fbe362d)

**Comment by haiiliin** [comment]
Thanks, I confused `displayGroupMdbToolset` and `displayGroupOdbToolset`

**Comment by haiiliin** [comment]
Please use new version `20**.5.6` for the fix

**Comment by keblicuey** [comment]
Thanks. It's resolved.
