### ISSUE TITLE
Unable to use Visual Studio Code debugger with ABQPY

### ISSUE THREAD

**Issue by prince2110** [haiiliin/abqpy#4936]
**Describe the bug**
VS Code debugger is not able to access data from ODB. When I use terminal to execute code (example code is provided below), the output is as expected but when I use VS Code debugger, then I get empty dictionary as output.

**To Reproduce**

1. Open VS Code
2. Launch Terminal
3. Activate approporiate environment in which ABQPY is installed
4. At First, run 'test.py' to obtain desired output.
5. Then use Debugger to check the output.
6. See difference between both executions

**Reproducible Code**
Simple example script:

```python
from odbAccess import *
from abaqusConstants import *
from textRepr import *
from shutil import copyfile
from os import getcwd, path
import numpy as np
import pprint
import time
import sys
import os

workingDir=os.getcwd()
odbName="test" #"ThroughThicknessCrackInInfinitePlane"
odbPath = os.path.normpath(odbName+".odb")

odb = openOdb(path=odbPath,readOnly=True)
root=odb.rootAssembly
instances_ = root.instances
print(instances_)
```

**Expected output when executed from terminal**
```
$ python test.py 

------------------------------------------------------------------------------
Running the following command: /opt/abaqus/2020/commands/abaqus python test.py
------------------------------------------------------------------------------
{'PLATE-1': 'OdbInstance object'}
```

**Output when using VS code debugger**
```
{}
```

**Comment by diogo-rossi** [comment]
It does not support debugging because Abaqus does not provide a debugger for Python scripting outside Abaqus/CAE.

Please, see this [warnning](https://docs.abqpy.com/en/stable/getting_started.html#run-your-abaqus-python-script:~:text=for%20more%20information.-,Warning,-abqpy%20does%20not).

**Comment by haiiliin** [comment]
We may need to print a warning message when running the script in debug mode.

**Comment by diogo-rossi** [comment]
@prince2110 if you want to debug a script in Abaqus in the terminal it is possible to use the module `pdb` ([The Python Debugger](https://docs.python.org/2/library/pdb.html))
Which is internal of python since version 2 and can be used in Abaqus.

It does not contain all modern features of advanced debuggers, but can do mostly of the job.
