### ISSUE TITLE
"pi" and "sqrt" could no longer be recognized automatically after abqpy was updated from 2023.5.5 to 2023.5.6

### ISSUE THREAD

**Issue by lizhoukan1** [haiiliin/abqpy#4979]
**Describe the bug**
I just updated from abqpy 2023.5.5 to 2023.5.6, and it appears that both "pi" and "sqrt" are no longer recognized unless I use "from math import pi, sqrt".

**Screenshots**
![image](https://github.com/haiiliin/abqpy/assets/32449835/17f4582a-142a-44be-8fa8-b6d9681ab41e)
![image](https://github.com/haiiliin/abqpy/assets/32449835/3259288b-91e7-4f66-9ccc-002e8dfdc047)
![image](https://github.com/haiiliin/abqpy/assets/32449835/c603c595-6152-41f5-9744-e40e51838b52)

**Additional context**
In the Kernal Command Line Interface of Abaqus, without importing anything, both "pi" and "sqrt" can be recognized.
![image](https://github.com/haiiliin/abqpy/assets/32449835/331801d8-546f-4c1f-a9c7-ba07862601d4)

**Comment by haiiliin** [comment]
Thanks for the report, the bug seems to be introduced in #4895.
