### ISSUE TITLE
Conversion of odb files in old and new versions of abaqus with abqpy

### ISSUE THREAD

**Issue by keblicuey** [haiiliin/abqpy#5262]
**Describe the bug**
I generated the odb file after calculating with abaqus2021. While I try to do something else with these odb files in abaqus2022, mistakes appeared. How can I use ‘’session.openOdb‘’ if the version of abaqus to generate odb files and open these files are not the same.

**Screenshots**
![image](https://github.com/haiiliin/abqpy/assets/81084513/4c4eadd2-c580-46d8-8293-0cf3ed7fea1e)

**Comment by haiiliin** [comment]
Try `odbAccess.upgradeOdb` to upgrade the old file or upgrade the odb file in Abaqus CAE

**Comment by keblicuey** [comment]
Thanks. It works.
