### ISSUE TITLE
Is it possible to print information to assist in development?

### ISSUE THREAD

**Issue by studyhardhardhard** [haiiliin/abqpy#5401]
from abaqus_noGUI import *
print("Hello world")
exit("Error")

I successfully installed the code abqpy and tried to develop it, but I ran into a problem, that is, when my program was running, I always wanted it to print some tips for me, so that I could better grasp the running status of the program. These tips may be very important in the case of difficult debugging.
But I don't know why, maybe because of the 2.7 kernel of abaqus and python3 of abqpy. In short, the program printing was ignored, the second line above did not play any role, and the third line reported the error TypeError:' str' object is not callable.
I developed abaqus on the ide of pycharm. In abaqus software, I can use python2 version of print to print, but now I don't know how to print after using abqpy. I look forward to anyone's help. Very grateful.

**Comment by haiiliin** [comment]
The printed messages are shown in the Abaqus/CAE console, you will need to use the GUI mode to run the script. You can set the [`ABAQUS_CAE_GUI`](https://haiiliin.github.io/abqpy/en/2023/envvars.html#envvar-ABAQUS_CAE_GUI) environment variable to `true` and ABAQUS/CAE will be opened if you run the script.

**Comment by studyhardhardhard** [comment]
Thank you for your answer. I did find the output I wanted in Abaqus/CAE console.
However, a better method is obviously to use noGUI to call the script and display the desired output on the command line at the same time. Is there any feasible method?

**Comment by haiiliin** [comment]
I don't find any way to do this

**Comment by haiiliin** [comment]
I found out that we can restore `sys.stdout` to force to print messages to the terminal, i.e.,

```python
import sys

from abaqus import *

sys.stdout = sys.__stdout__
print("Hello, world!")
```

**Comment by studyhardhardhard** [comment]
Thank you for your prompt response.
It worked, but not completely.

I am using your abqpy for ABAQUS secondary development in PyCharm.
When I run the code by typing "python mycode.py" in the command line terminal, the information I want to output is printed in the command line terminal.
However, when I use PyCharm to run the code, the information to be output is not printed in the PyCharm console.

I have also done some research recently. When I start the Abaqus process from PyCharm, Abaqus defaults to taking over the output stream, and there is no simple way to redirect this output stream back to PyCharm easily. I might just have to accept this fact.
Thank you again for your answer, and I look forward to hearing if you have any better ideas.

**Comment by haiiliin** [comment]
I just tested the code in PyCharm, and it works fine for me.

![image](https://github.com/haiiliin/abqpy/assets/47051427/832a1cb6-c6e8-4f31-a56b-214b87b96a46)

**Comment by studyhardhardhard** [comment]
Thank you for your response. I have carefully reviewed my code and discovered a very interesting phenomenon.

In another program that I wrote and imported into my code, there was an output like this:
print('the result is ', resultant_force[0], resultant_force[1], resultant_force[2])
where resultant_force is a 1x3 array.
Surprisingly, this output was causing my issue, as it was the reason why there was no output after running my code.

If I simply modify it to: print('the result is ', resultant_force), without changing anything else, it outputs: ('the result is ', array([51.7550154759483, -0.0659758502744336, 28.8125464945722], 'd'))
If I modify it to: print('the result is ' + str(resultant_force[0]) + ' ' + str(resultant_force[1]) + ' ' + str(resultant_force[2])), it outputs: the result is 51.7550154759 -0.0659758502744 28.8125464946
Note that in this case, there are no parentheses. Both of these methods work effectively, and at the same time, all my other prints output normally, whereas previously, there was no output from my manual prints in the PyCharm console.

I tried to strip it down to a simple test, that is, only test the relevant code and strip away all irrelevant parts. Unfortunately, it might be because it did not enter the Abaqus kernel, print('the result is ', resultant_force[0], resultant_force[1], resultant_force[2]) outputs:('the resultant_force integrated by inp is ', 51.7550154759483, -0.0659758502744336, 28.8125464945722)
So at this time, it again had no issues and could output normally.

Therefore, my solution was to modify my print expression to one of the above that could output normally.
It might be related to Python 2's tuple printing, but strangely, it did not throw an error, it just did not output anything. Moreover, my stripped-down code part did not have this issue. I originally wanted to replicate my problem with simple code, but due to time constraints, I decided not to.
Thank you again for your response. Your development of adqpy has been very useful to me.
Regards

**Comment by diogo-rossi** [comment]
@studyhardhardhard hello there! Happy 2025!

> It might be related to Python 2's tuple printing

It is exactly that!
Python 2 has a default "print statement" (not a function), as you can see in the [documentation](https://docs.python.org/2/reference/simple_stmts.html#the-print-statement).

When you use `print(something)`, it does not use a function: it just print `(something)` which is expanded to `something` as it normally does for [tuples declared with only one element](https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences:~:text=A%20special%20problem,effective.%20For%20example%3A).

When you use `print (something, anotherthing)` it used the print statement again (not a function)
then, the tuple `(something, anotherthing)` is printed.

```python
Python 2.7.15 (default, Jul 25 2019, 08:13:50) [MSC v.1916 64 bit (AMD64)]
>>> print "Diogo", "Rossi" # print statement with 2 strings
Diogo Rossi
>>> print("Diogo", "Rossi") # print statement printing the tuple ("Diogo", "Rossi") 
('Diogo', 'Rossi')
```

However, you can [disable the print statement and use the print() function](https://docs.python.org/2/library/functions.html#print) if you want:

```python
Python 2.7.15 (default, Jul 25 2019, 08:13:50) [MSC v.1916 64 bit (AMD64)]
>>> from __future__ import print_function
>>> print("Diogo", "Rossi")
Diogo Rossi
```

**Comment by diogo-rossi** [comment]
> I found out that we can restore `sys.stdout` to force to print messages to the terminal, i.e.,

Another way to do that is using the [python 2 print statement "chevron" (>>)](https://docs.python.org/2/reference/simple_stmts.html#the-print-statement) to redirect the output.
The original definition of Python's standard output is stored in `sys.__stdout__`, so you can use:

```python
import sys
print >> sys.__stdout__, "Hello, world!"
```
And it gets printed to the terminal, without modifying the Abaqus internal definition of `sys.stdout`

reference: https://stackoverflow.com/a/36567169/9761768
