### ISSUE TITLE
Willing to make a PR, and I have some questions

### ISSUE THREAD

**Issue by huibosa** [haiiliin/abqpy#5555]
I've notice that the package does not have the correct type hints for some of the functions, such as the one in Feature.py:

```
def DataumAxisByTwoPoint(
        self,
        point1: int,
        point2: int
) -> Feature:
        ...
```

According to the docstring you provide, I would like to make the following change:

```
 def DatumAxisByTwoPoint(
        self,
        point1: Union[ConstrainedSketchVertex, DatumPoint, MeshNode, InterestingPoint, Sequence[float], NDArray],
        point2: Union[ConstrainedSketchVertex, DatumPoint, MeshNode, InterestingPoint, Sequence[float], NDArray],
) -> Feature:
```

Note that I've made some changes in addition to the types you have described in the docstring:

* `Datum` -> `DatumPoint`.
* Adding `Sequence[float]` since the function requires a point.
* Adding `numpy.typing.NDarray` since abaqus always allow a numpy array be passed to a parameter which reeuqires a tuple.

Please consider the above three changes and tell me if any of them is inappropriate.

**Comment by haiiliin** [comment]
Great, thanks. There are probably many errors like this, happy to receive PRs.
