### ISSUE TITLE
`AbaqusException` missing as importable from `'abaqus'`

### ISSUE THREAD

**Issue by sebastianvitterso** [haiiliin/abqpy#5609]
**Describe the bug**
The `'abaqus'` module contains the `AbaqusException` class, which is sometimes raised by Abaqus.

**To Reproduce**

Tested using Abaqus CAE:

```python
# test.py
from abaqus import AbaqusException
with open("log.out", "a") as f:
  print(AbaqusException, file=f)
```

```bash
# in terminal
$ abaqus cae noGUI=test.py
```

```python
# log.out
<class 'AbaqusException'>
```

This final output shows that the import succeeded, meaning the `AbaqusException` class can be imported from `'abaqus'`.

**Reproducible Code**
Se above.

**Expected behavior**
I'd expect to see the `AbaqusException` class as importable from `'abaqus'`. Basically, we just need as spoof of the ExceptionClass.

**Screenshots**
![image](https://github.com/haiiliin/abqpy/assets/37065184/f980076c-5688-4b55-82a0-0a5696032c2d)
![image](https://github.com/haiiliin/abqpy/assets/37065184/a96fdbeb-44d7-45f2-8f95-4f3097b54944)

**Comment by haiiliin** [comment]
AbaqusException is not documented in the abaqus scripting reference, I will add it later.

**Comment by sebastianvitterso** [comment]
Thank you!
