### ISSUE TITLE
`mdb.models[name].SurfaceToSurfaceContactStd` should replace `master` and `slave` with `main` and `secondary` respectively

### ISSUE THREAD

**Issue by sebastianvitterso** [haiiliin/abqpy#5718]
**Describe the bug**
The start of the function's (type-) definition looks like this in abqpy:
```py
    def SurfaceToSurfaceContactStd(
        self,
        name: str,
        createStepName: str,
        master: Region,
        slave: Region,
        sliding: Literal[C.SMALL, C.FINITE],
        interactionProperty: str,
        ... (optionals)
```

however, looking in Abaqus2024 Scripting Reference, I can't find these `master` and `slave` arguments anywhere, particularly not among the required parameters. It seems they have been replaced with `main` and `secondary`.
![image](https://github.com/user-attachments/assets/31925243-6068-47a3-bdc2-1d49a63da5f7)

I see that `abqpy` has made this transition for some parameters already (e.g. in neighboring `SurfaceToSurfaceContactExp`).

**Comment by sebastianvitterso** [comment]
I see that the same is true for `Material.py`, where `Material.GapRadiation` takes `master-` and `slaveSurfaceEmissivity`, which seem to have been updated in the 2024 scripting reference (maybe even 2022, as you say in some docstrings).

**Comment by haiiliin** [comment]
Thanks, many arguments concerned with master and slave were renamed in Abaqus 2022, and some methods were missed to be updated.

**Comment by sebastianvitterso** [comment]
I must say I love that you work so actively on these fixes - makes using the project a breeze.
