### ISSUE TITLE
`Odb.FieldValue.data` is typed only as `tuple`, but should be typed as `tuple[float]` 

### ISSUE THREAD

**Issue by sebastianvitterso** [haiiliin/abqpy#5731]
**Describe the bug**
In `abqpy/Odb/FieldValue.py:144-152`:
```py
    #: A tuple of Floats specifying data in the form described by **type**. If **type** = TENSOR or
    #: VECTOR, **data** is a sequence containing the components. If the underlying data are in
    #: double precision an exception will be thrown.
    data: tuple = ()

    #: A tuple of Floats specifying data in the form described by **type**. If **type** = TENSOR or
    #: VECTOR, **data** is a sequence containing the components. If the underlying data are in
    #: single precision, an exception will be thrown.
    dataDouble: tuple = ()
```

The docstrings say that these are tuples of floats, so the typing could reflect this.

Proposed solution is simple: 

```py
    #: A tuple of Floats specifying data in the form described by **type**. If **type** = TENSOR or
    #: VECTOR, **data** is a sequence containing the components. If the underlying data are in
    #: double precision an exception will be thrown.
    data: tuple[float] = ()

    #: A tuple of Floats specifying data in the form described by **type**. If **type** = TENSOR or
    #: VECTOR, **data** is a sequence containing the components. If the underlying data are in
    #: single precision, an exception will be thrown.
    dataDouble: tuple[float] = ()
```

**Comment by haiiliin** [comment]
There is too much work to do about this kind of typing error.

**Comment by sebastianvitterso** [comment]
Hm, I see. 1655 cases are a lot, and many of them are more complicated than this one (with tuples of tuples of enum values). I don't think I'll be able to help with the more complex cases, but I could attempt the simpler ones, and spend some time on that, if that is helpful. But if consistency is a higher priority than having precision in certain places, which I would understand, then I won't be able to assist, given that I won't reach over the whole project.

Thoughts?

**Comment by haiiliin** [comment]
Any small fixes are welcome

**Comment by haiiliin** [comment]
> Proposed solution is simple: 
> 
> ```py
>     #: A tuple of Floats specifying data in the form described by **type**. If **type** = TENSOR or
>     #: VECTOR, **data** is a sequence containing the components. If the underlying data are in
>     #: double precision an exception will be thrown.
>     data: tuple[float] = ()
> 
>     #: A tuple of Floats specifying data in the form described by **type**. If **type** = TENSOR or
>     #: VECTOR, **data** is a sequence containing the components. If the underlying data are in
>     #: single precision, an exception will be thrown.
>     dataDouble: tuple[float] = ()
> ```
> 

`tuple[float, ...]` should be better because `tuple[float]` represents a tuple with exactly one float.
