### ISSUE TITLE
how to compile python file in abqpy environment? 

### ISSUE THREAD

**Issue by xiaoscofield** [haiiliin/abqpy#5826]
In the environment abqpy 2017 and abaqus 2017, I compiled my file of run_computaion.py
import py_compile
py_compile.compile('run_computation.py')

then, we use the following python program to call run_computation function,
import importlib.util
import sys
pyc_file_path = 'D:\\Simulation_Temp\\Asimco_python_develop\\abqpy-2024\\tests\\__pycache__\\run_computation.cpython-310.pyc'

spec = importlib.util.spec_from_file_location("run_computation", pyc_file_path)
run_computation = importlib.util.module_from_spec(spec)
sys.modules["run_computation"] = run_computation
spec.loader.exec_module(run_computation)

finally, it gives errors listed below,

ImportError: No module named util
File "call_run_computation.py", line 12, in <module>
    import importlib.util

how to solve it?

**Comment by haiiliin** [comment]
I don't think you can do something like this. The only purpose of abqpy is to provide type hints.

**Comment by xiaoscofield** [comment]
> I don't think you can do something like this. The only purpose of abqpy is to provide type hints.

hi boss, I compiled the python file with following program,  
import py_compile
py_compile.compile('run_computation.py')

then, I changed the name of pyc file, the original name is run_computation.cpython-310.pyc, and the new name is run_computation.pyc.

I run the main program below, 
import sys
sys.path.append('D:\\Simulation_Temp\\Asimco_python_develop\\abqpy-2024\\tests\\pyc_test')
import run_computation

and the following error is given.
ImportError: Bad magic number in D:\Simulation_Temp\Asimco_python_develop\abqpy-2024\tests\pyc_test\run_computation.pyc
File "call_run_computation.py", line 32, in <module>
    import run_computation

I confirmed that the current python version is 3.10, do you think that it is necessary to compile the python file in the abaqus 2017 environment(python 2.7 is installed)?

**Comment by xiaoscofield** [comment]
with abqpy 2017 and abaqus 2017, we can use Parallel computing to prove program efficiency performance. and in order to protect privacy, is there some way to compile python file conveniently?

**Comment by haiiliin** [comment]
Maybe you need to compile the file using the abaqus's python interpreter because it contains the real implementations of the abaqus python libraries.

**Comment by haiiliin** [comment]
Compiling python into pyc files does not actually protect your code well, it can be easily decompiled.

**Comment by xiaoscofield** [comment]
I compiled the python file in folder with python program listed below in the folder D:\Abaqus2017\Product\win_b64\tools\SMApy\python2.7
python2.7 -m py_compile run_computation.py

it still shows the magic number error
Traceback (most recent call last):
  File "D:\Simulation_Temp\Asimco_python_develop\abqpy-2024\tests\pyc_test\call_run_computation.py", line 32, in <module>
    import run_computation
ImportError: bad magic number in 'run_computation': b'\x03\xf3\r\n'
the magic number 0x03F3 shows the version python 3.10, I don't know how to fix it.

**Comment by xiaoscofield** [comment]
> Maybe you need to compile the file using the abaqus's python interpreter because it contains the real implementations of the abaqus python libraries.

please check it. compile in the abaqus 2.17 environment, magic number error still exists.

**Comment by xiaoscofield** [comment]
nice to meet you, I am a huster in wuxi

**Comment by haiiliin** [comment]
The magic number error means the python version you compile the file does not match the python version you run the compiled file. Abaqus's python is version 2.7, so you need to compile the file using abaqus python 2.7 instead of python 3.10.

**Comment by haiiliin** [comment]
> nice to meet you, I am a huster in wuxi

What a coincidence, I got my bachelor degree in HUST.

**Comment by ZhangKf-Lib** [comment]
Hi, is it possible to run the code directly using python 3.12.4? (e.g. run the code in pycharm instead of abaqusPDE)

**Comment by haiiliin** [comment]
> Hi, is it possible to run the code directly using python 3.12.4? (e.g. run the code in pycharm instead of abaqusPDE)
> 
>

If you want to debug the script in PyCharm, it is not possible. Otherwise, running scripts in PyCharm will call the abaqus command to submit it to abaqus.
