### ISSUE TITLE
Support GUI Toolkit Commands

### ISSUE THREAD

**Issue by haiiliin** [haiiliin/abqpy#631]
Currently the [Abaqus GUI Toolkit Commands](https://help.3ds.com/2022/English/DSSIMULIA_Established/SIMACAEGUIRefHtml/simagui-c-ov.htm?contextscope=all) are not supported.

**Comment by haiiliin** [comment]
Close this in favor of #277.

**Comment by Spectre5** [comment]
wow, incredible, I'll certainly be interested in testing this out!
